// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef DrawHistoryManagerGUI_h
#define DrawHistoryManagerGUI_h
#include <FL/Fl.H>
#include <string>
#include "defs.h"
#include "types.h"
#include "ResultDownloader.h"
#include "ResultManager.h"
#include "HistoricResults.h"
#include "ResultViewTable.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Progress.H>

class DrawHistoryManagerGUI {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *main_window;
  Fl_Output *tatts_last_draw;
  Fl_Output *ozlotto_last_draw;
  Fl_Output *powerball_last_draw;
  Fl_Output *sfl_last_draw;
  Fl_Output *ozlotto_last_date;
  Fl_Output *powerball_last_date;
  Fl_Output *sfl_last_date;
  Fl_Output *tatts_last_date;
private:
  inline void cb_Update_i(Fl_Button*, void*);
  static void cb_Update(Fl_Button*, void*);
  inline void cb_View_i(Fl_Button*, void*);
  static void cb_View(Fl_Button*, void*);
  inline void cb_View1_i(Fl_Button*, void*);
  static void cb_View1(Fl_Button*, void*);
  inline void cb_View2_i(Fl_Button*, void*);
  static void cb_View2(Fl_Button*, void*);
  inline void cb_View3_i(Fl_Button*, void*);
  static void cb_View3(Fl_Button*, void*);
public:
  ResultViewTable *resultViewTable;
  Fl_Output *weekday_last_date;
private:
  inline void cb_View4_i(Fl_Button*, void*);
  static void cb_View4(Fl_Button*, void*);
public:
  Fl_Output *weekday_last_draw;
  Fl_Double_Window *update_window;
  Fl_Check_Button *tatts_c;
  Fl_Check_Button *ozlotto_c;
  Fl_Check_Button *powerball_c;
  Fl_Check_Button *sfl_c;
  Fl_Check_Button *weekday_tatts_c;
  Fl_Progress *update_progress_bar;
  static void update_results(Fl_Widget* w, void* userdata);
  virtual void update_results_callback(Fl_Widget* w, void* userdata) = 0;
  static void hide_parent(Fl_Widget *w, void* data);
  virtual void init_result_view(resultType type) = 0;
};
#endif
