// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef ResultManagerGUI_h
#define ResultManagerGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Output.H>

class ResultManagerGUI {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *ResultManagerGUI;
  static Fl_Menu_Item menu_Update[];
};
#endif
