// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "AussieLottoGUI.h"
/* Aussie Lotto */
#include <FL/fl_ask.H>
#include "defs.h"

void UserInterface::cb_Quit_i(Fl_Button*, void*) {
  quit();
}
void UserInterface::cb_Quit(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Quit_i(o,v);
}

void UserInterface::cb_Open_i(Fl_Menu_*, void*) {
  open_file();
}
void UserInterface::cb_Open(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Open_i(o,v);
}

void UserInterface::cb_Save_i(Fl_Menu_*, void*) {
  save_file();
}
void UserInterface::cb_Save(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Save_i(o,v);
}

void UserInterface::cb_Exit_i(Fl_Menu_*, void*) {
  quit();
}
void UserInterface::cb_Exit(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Exit_i(o,v);
}

Fl_Menu_Item UserInterface::menu_File[] = {
 {"Open", 0,  (Fl_Callback*)UserInterface::cb_Open, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save", 0,  (Fl_Callback*)UserInterface::cb_Save, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Exit", 0,  (Fl_Callback*)UserInterface::cb_Exit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void UserInterface::cb_About_i(Fl_Button*, void*) {
  fl_message("Aussie Lotto\nWritten by Dennis Katsonis, April 2014.\nVersion " PROG_VERSION"\n(C) Dennis Katsonis 2014\nLicensed under the GPL3.  See 'License' for more details");
}
void UserInterface::cb_About(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_About_i(o,v);
}

void UserInterface::cb_Generate_i(Fl_Button*, void*) {
  generate();
}
void UserInterface::cb_Generate(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Generate_i(o,v);
}

void UserInterface::cb_Check_i(Fl_Button*, void*) {
  check_lotto();
}
void UserInterface::cb_Check(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Check_i(o,v);
}

void UserInterface::cb_Check1_i(Fl_Menu_*, void*) {
  check_lotto();
}
void UserInterface::cb_Check1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Check1_i(o,v);
}

void UserInterface::cb_Generate1_i(Fl_Menu_*, void*) {
  generate();
}
void UserInterface::cb_Generate1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Generate1_i(o,v);
}

void UserInterface::cb_Clear_i(Fl_Menu_*, void*) {
  clear_lotto();
}
void UserInterface::cb_Clear(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Clear_i(o,v);
}

void UserInterface::cb_Clear1_i(Fl_Menu_*, void*) {
  clear_results();
}
void UserInterface::cb_Clear1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Clear1_i(o,v);
}

void UserInterface::cb_Result_i(Fl_Menu_*, void*) {
  dhm->main_window->show();
}
void UserInterface::cb_Result(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Result_i(o,v);
}

Fl_Menu_Item UserInterface::menu_Options[] = {
 {"Check", 0,  (Fl_Callback*)UserInterface::cb_Check1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Generate", 0,  (Fl_Callback*)UserInterface::cb_Generate1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Clear Numbers", 0,  (Fl_Callback*)UserInterface::cb_Clear, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Clear Lottery Results", 0,  (Fl_Callback*)UserInterface::cb_Clear1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Result Manager", 0,  (Fl_Callback*)UserInterface::cb_Result, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void UserInterface::cb_Help_i(Fl_Button*, void*) {
  show_help_window();
}
void UserInterface::cb_Help(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Help_i(o,v);
}

void UserInterface::cb_tabular_i(Fl_Tabs*, void*) {
  changeTab();
}
void UserInterface::cb_tabular(Fl_Tabs* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_tabular_i(o,v);
}

void UserInterface::cb_Enter_i(Fl_Button*, void*) {
  show_Numberentry_window();
}
void UserInterface::cb_Enter(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_Enter_i(o,v);
}

void UserInterface::cb_Enter1_i(Fl_Button*, void*) {
  show_Numberentry_window();
}
void UserInterface::cb_Enter1(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_Enter1_i(o,v);
}

void UserInterface::cb_ensurePowerball_i(Fl_Check_Button*, void*) {
  ensurePowerballButton();
}
void UserInterface::cb_ensurePowerball(Fl_Check_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_ensurePowerball_i(o,v);
}

void UserInterface::cb_Enter2_i(Fl_Button*, void*) {
  show_Numberentry_window();
}
void UserInterface::cb_Enter2(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_Enter2_i(o,v);
}

Fl_Menu_Item UserInterface::menu_Winning[] = {
 {"Tattslotto", 0,  (Fl_Callback*)show_divisions, (void*)(TATTSLOTTO), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Oz Lotto", 0,  (Fl_Callback*)show_divisions, (void*)(OZLOTTO), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Powerball", 0,  (Fl_Callback*)show_divisions, (void*)(POWERBALL), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Lotto Strike", 0,  (Fl_Callback*)show_divisions, (void*)(LOTTOSTRIKE), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Set For Life", 0,  (Fl_Callback*)show_divisions, (void*)(SET_FOR_LIFE), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void UserInterface::cb_License_i(Fl_Button*, void*) {
  show_license_window();
}
void UserInterface::cb_License(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_License_i(o,v);
}

void UserInterface::cb_Save1_i(Fl_Button*, void*) {
  saveResults();
}
void UserInterface::cb_Save1(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Save1_i(o,v);
}

void UserInterface::cb_OK_i(Fl_Button*, void*) {
  tattsEntry();
}
void UserInterface::cb_OK(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_OK_i(o,v);
}

void UserInterface::cb_OK1_i(Fl_Button*, void*) {
  ozlottoEntry();
}
void UserInterface::cb_OK1(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_OK1_i(o,v);
}

void UserInterface::cb_OK2_i(Fl_Button*, void*) {
  lottostrikeEntry();
}
void UserInterface::cb_OK2(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_OK2_i(o,v);
}

void UserInterface::cb_OK3_i(Fl_Button*, void*) {
  setForLifeEntry();
}
void UserInterface::cb_OK3(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_OK3_i(o,v);
}

void UserInterface::cb_OK4_i(Fl_Button*, void*) {
  submitButtonNums();
}
void UserInterface::cb_OK4(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_OK4_i(o,v);
}

void UserInterface::cb_OK5_i(Fl_Button*, void*) {
  powerballEntry();
}
void UserInterface::cb_OK5(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_OK5_i(o,v);
}

Fl_Window* UserInterface::make_window() {
  { lotto_gui = new Fl_Window(670, 625, "Aussie Lotto");
    lotto_gui->color((Fl_Color)14);
    lotto_gui->selection_color(FL_GRAY0);
    lotto_gui->labelcolor((Fl_Color)12);
    lotto_gui->user_data((void*)(this));
    lotto_gui->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    lotto_gui->when(FL_WHEN_RELEASE_ALWAYS);
    { Fl_Box* o = new Fl_Box(0, 0, 670, 45, "Aussie Lotto");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->selection_color(FL_BACKGROUND2_COLOR);
      o->labeltype(FL_SHADOW_LABEL);
      o->labelfont(1);
      o->labelsize(26);
      o->labelcolor((Fl_Color)1);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(570, 55, 100, 25, "Quit");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)cb_Quit);
    } // Fl_Button* o
    { Fl_Menu_Button* o = new Fl_Menu_Button(5, 55, 75, 25, "File");
      o->color((Fl_Color)14);
      o->menu(menu_File);
    } // Fl_Menu_Button* o
    { Fl_Button* o = new Fl_Button(415, 55, 80, 25, "About");
      o->color((Fl_Color)14);
      o->selection_color((Fl_Color)6);
      o->callback((Fl_Callback*)cb_About);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(5, 85, 125, 35, "Generate Numbers");
      o->color((Fl_Color)137);
      o->selection_color(FL_FOREGROUND_COLOR);
      o->labelfont(1);
      o->labelcolor(FL_RED);
      o->callback((Fl_Callback*)cb_Generate);
      o->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(135, 85, 135, 35, "Check Numbers");
      o->color((Fl_Color)138);
      o->selection_color(FL_FOREGROUND_COLOR);
      o->labelfont(1);
      o->labelcolor(FL_RED);
      o->callback((Fl_Callback*)cb_Check);
      o->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* o
    { num_games = new Fl_Value_Input(460, 85, 95, 30, "Number of Games");
      num_games->color(FL_FOREGROUND_COLOR);
      num_games->textfont(1);
      num_games->textsize(16);
      num_games->textcolor((Fl_Color)3);
    } // Fl_Value_Input* num_games
    { Fl_Menu_Button* o = new Fl_Menu_Button(80, 55, 90, 25, "Options");
      o->color((Fl_Color)14);
      o->menu(menu_Options);
    } // Fl_Menu_Button* o
    { Fl_Button* o = new Fl_Button(330, 55, 85, 25, "Help");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)cb_Help);
    } // Fl_Button* o
    { tabular = new Fl_Tabs(0, 125, 670, 605);
      tabular->box(FL_THIN_DOWN_BOX);
      tabular->labeltype(FL_NO_LABEL);
      tabular->callback((Fl_Callback*)cb_tabular);
      tabular->align(Fl_Align(37));
      { tattslotto_tab = new Fl_Group(0, 145, 670, 475, "Tattslotto/Gold Lotto/X Lotto");
        tattslotto_tab->box(FL_DOWN_BOX);
        tattslotto_tab->color(FL_DARK_CYAN);
        tattslotto_tab->selection_color((Fl_Color)29);
        tattslotto_tab->labeltype(FL_EMBOSSED_LABEL);
        { Fl_Group* o = new Fl_Group(20, 170, 280, 45, "Lottery Numbers");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)6);
          o->labelsize(16);
          { num1 = new Fl_Value_Input(45, 180, 35, 30);
            num1->color((Fl_Color)58);
            num1->textsize(16);
            num1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num1
          { num2 = new Fl_Value_Input(85, 180, 35, 30);
            num2->color((Fl_Color)58);
            num2->textsize(16);
            num2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num2
          { num3 = new Fl_Value_Input(125, 180, 35, 30);
            num3->color((Fl_Color)58);
            num3->textsize(16);
            num3->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num3
          { num4 = new Fl_Value_Input(165, 180, 35, 30);
            num4->color((Fl_Color)58);
            num4->textsize(16);
            num4->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num4
          { num5 = new Fl_Value_Input(205, 180, 35, 30);
            num5->color((Fl_Color)58);
            num5->textsize(16);
            num5->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num5
          { num6 = new Fl_Value_Input(245, 180, 35, 30);
            num6->color((Fl_Color)58);
            num6->textsize(16);
            num6->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num6
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(315, 170, 135, 45, "Supplementaries");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)222);
          o->labelsize(16);
          { supp1 = new Fl_Value_Input(335, 180, 35, 30);
            supp1->color((Fl_Color)59);
            supp1->selection_color((Fl_Color)58);
            supp1->labelcolor((Fl_Color)3);
            supp1->textsize(16);
            supp1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* supp1
          { supp2 = new Fl_Value_Input(375, 180, 35, 30);
            supp2->color((Fl_Color)59);
            supp2->selection_color((Fl_Color)58);
            supp2->labelcolor((Fl_Color)3);
            supp2->textsize(16);
            supp2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* supp2
          o->end();
        } // Fl_Group* o
        { Fl_Text_Display* o = number_view = new Fl_Text_Display(15, 250, 410, 355, "Lottery Numbers");
          number_view->box(FL_THIN_DOWN_BOX);
          number_view->color(FL_FOREGROUND_COLOR);
          number_view->selection_color(FL_FOREGROUND_COLOR);
          number_view->labeltype(FL_ENGRAVED_LABEL);
          number_view->labelsize(22);
          number_view->labelcolor((Fl_Color)80);
          number_view->textfont(13);
          number_view->textcolor((Fl_Color)2);
          o->buffer(tattslottoTextBuffer);
        } // Fl_Text_Display* number_view
        { ShowTattsEntryWidget = new Fl_Button(440, 235, 120, 60, "Enter numbers with form");
          ShowTattsEntryWidget->color((Fl_Color)14);
          ShowTattsEntryWidget->callback((Fl_Callback*)show_entry_window, (void*)(TATTSLOTTO));
          ShowTattsEntryWidget->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* ShowTattsEntryWidget
        { Fl_Button* o = new Fl_Button(440, 305, 120, 60, "Enter numbers with buttons");
          o->color((Fl_Color)14);
          o->callback((Fl_Callback*)cb_Enter);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* o
        { t_draw = new Fl_Value_Input(460, 160, 60, 25);
        } // Fl_Value_Input* t_draw
        { Fl_Button* o = new Fl_Button(455, 205, 140, 25, "Use Draw Results");
          o->callback((Fl_Callback*)use_draw_results, (void*)(R_TATTSLOTTO));
        } // Fl_Button* o
        { radiobuttons = new Fl_Group(525, 145, 145, 60);
          { weekday_but = new Fl_Round_Button(530, 175, 135, 25, "Mon, Wed Lotto");
            weekday_but->type(102);
            weekday_but->down_box(FL_ROUND_DOWN_BOX);
          } // Fl_Round_Button* weekday_but
          { sat_but = new Fl_Round_Button(530, 145, 140, 30, "Saturday Lotto");
            sat_but->type(102);
            sat_but->down_box(FL_ROUND_DOWN_BOX);
            sat_but->value(1);
          } // Fl_Round_Button* sat_but
          radiobuttons->end();
        } // Fl_Group* radiobuttons
        tattslotto_tab->end();
      } // Fl_Group* tattslotto_tab
      { ozlotto_tab = new Fl_Group(0, 145, 670, 475, "OzLotto");
        ozlotto_tab->box(FL_DOWN_BOX);
        ozlotto_tab->color(FL_DARK_GREEN);
        ozlotto_tab->labeltype(FL_EMBOSSED_LABEL);
        ozlotto_tab->hide();
        { Fl_Group* o = new Fl_Group(20, 170, 335, 45, "Oz Lotto Numbers");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)6);
          o->labelsize(16);
          { oz_num1 = new Fl_Value_Input(45, 180, 35, 30);
            oz_num1->color((Fl_Color)58);
            oz_num1->textsize(16);
            oz_num1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num1
          { oz_num2 = new Fl_Value_Input(85, 180, 35, 30);
            oz_num2->color((Fl_Color)58);
            oz_num2->textsize(16);
            oz_num2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num2
          { oz_num3 = new Fl_Value_Input(125, 180, 35, 30);
            oz_num3->color((Fl_Color)58);
            oz_num3->textsize(16);
            oz_num3->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num3
          { oz_num4 = new Fl_Value_Input(165, 180, 35, 30);
            oz_num4->color((Fl_Color)58);
            oz_num4->textsize(16);
            oz_num4->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num4
          { oz_num5 = new Fl_Value_Input(205, 180, 35, 30);
            oz_num5->color((Fl_Color)58);
            oz_num5->textsize(16);
            oz_num5->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num5
          { oz_num6 = new Fl_Value_Input(245, 180, 35, 30);
            oz_num6->color((Fl_Color)58);
            oz_num6->textsize(16);
            oz_num6->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num6
          { oz_num7 = new Fl_Value_Input(285, 180, 35, 30);
            oz_num7->color((Fl_Color)58);
            oz_num7->textsize(16);
            oz_num7->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num7
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(375, 170, 125, 45, "Supplementaries");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)222);
          o->labelsize(16);
          { oz_supp1 = new Fl_Value_Input(395, 180, 35, 30);
            oz_supp1->color((Fl_Color)59);
            oz_supp1->selection_color((Fl_Color)58);
            oz_supp1->labelcolor((Fl_Color)3);
            oz_supp1->textsize(16);
            oz_supp1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_supp1
          { oz_supp2 = new Fl_Value_Input(435, 180, 35, 30);
            oz_supp2->color((Fl_Color)59);
            oz_supp2->selection_color((Fl_Color)58);
            oz_supp2->labelcolor((Fl_Color)3);
            oz_supp2->textsize(16);
            oz_supp2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_supp2
          o->end();
        } // Fl_Group* o
        { Fl_Text_Display* o = oz_number_view = new Fl_Text_Display(15, 250, 410, 355, "Oz Lotto Numbers");
          oz_number_view->box(FL_THIN_DOWN_BOX);
          oz_number_view->color(FL_FOREGROUND_COLOR);
          oz_number_view->selection_color(FL_FOREGROUND_COLOR);
          oz_number_view->labeltype(FL_ENGRAVED_LABEL);
          oz_number_view->labelsize(22);
          oz_number_view->labelcolor((Fl_Color)80);
          oz_number_view->textfont(13);
          oz_number_view->textcolor((Fl_Color)2);
          Fl_Group::current()->resizable(oz_number_view);
          o->buffer(ozlottoTextBuffer);
        } // Fl_Text_Display* oz_number_view
        { ShowOzlottoEntryWidget = new Fl_Button(440, 235, 120, 60, "Enter numbers with form");
          ShowOzlottoEntryWidget->color((Fl_Color)10);
          ShowOzlottoEntryWidget->callback((Fl_Callback*)show_entry_window, (void*)(OZLOTTO));
          ShowOzlottoEntryWidget->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* ShowOzlottoEntryWidget
        { Fl_Button* o = new Fl_Button(440, 305, 120, 60, "Enter numbers with buttons");
          o->color((Fl_Color)10);
          o->callback((Fl_Callback*)cb_Enter1);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* o
        { o_draw = new Fl_Value_Input(555, 155, 70, 25);
        } // Fl_Value_Input* o_draw
        { Fl_Button* o = new Fl_Button(530, 180, 140, 25, "Use Draw Results");
          o->callback((Fl_Callback*)use_draw_results, (void*)(R_OZLOTTO));
        } // Fl_Button* o
        ozlotto_tab->end();
      } // Fl_Group* ozlotto_tab
      { powerball_tab = new Fl_Group(0, 145, 670, 585, "Powerball");
        powerball_tab->box(FL_DOWN_BOX);
        powerball_tab->color((Fl_Color)187);
        powerball_tab->labeltype(FL_EMBOSSED_LABEL);
        powerball_tab->hide();
        { Fl_Group* o = new Fl_Group(20, 170, 260, 45, "Powerball Numbers");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)6);
          o->labelsize(16);
          { pb_num1 = new Fl_Value_Input(35, 180, 35, 30);
            pb_num1->color((Fl_Color)58);
            pb_num1->textsize(16);
            pb_num1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num1
          { pb_num2 = new Fl_Value_Input(75, 180, 35, 30);
            pb_num2->color((Fl_Color)58);
            pb_num2->textsize(16);
            pb_num2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num2
          { pb_num3 = new Fl_Value_Input(115, 180, 35, 30);
            pb_num3->color((Fl_Color)58);
            pb_num3->textsize(16);
            pb_num3->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num3
          { pb_num4 = new Fl_Value_Input(155, 180, 35, 30);
            pb_num4->color((Fl_Color)58);
            pb_num4->textsize(16);
            pb_num4->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num4
          { pb_num5 = new Fl_Value_Input(195, 180, 35, 30);
            pb_num5->color((Fl_Color)58);
            pb_num5->textsize(16);
            pb_num5->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num5
          { pb_num6 = new Fl_Value_Input(235, 180, 35, 30);
            pb_num6->color((Fl_Color)58);
            pb_num6->textsize(16);
            pb_num6->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num6
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(300, 170, 90, 55, "Powerball");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)4);
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(16);
          { powerball_value = new Fl_Value_Input(320, 175, 50, 45);
            powerball_value->color((Fl_Color)59);
            powerball_value->selection_color((Fl_Color)58);
            powerball_value->labelsize(16);
            powerball_value->labelcolor((Fl_Color)6);
            powerball_value->textfont(1);
            powerball_value->textsize(18);
            powerball_value->textcolor((Fl_Color)6);
          } // Fl_Value_Input* powerball_value
          o->end();
        } // Fl_Group* o
        { Fl_Text_Display* o = powerball_number_view = new Fl_Text_Display(15, 250, 410, 355, "Powerball Numbers");
          powerball_number_view->box(FL_THIN_DOWN_BOX);
          powerball_number_view->color(FL_FOREGROUND_COLOR);
          powerball_number_view->selection_color(FL_FOREGROUND_COLOR);
          powerball_number_view->labeltype(FL_ENGRAVED_LABEL);
          powerball_number_view->labelsize(22);
          powerball_number_view->labelcolor((Fl_Color)80);
          powerball_number_view->textfont(13);
          powerball_number_view->textcolor((Fl_Color)2);
          Fl_Group::current()->resizable(powerball_number_view);
          o->buffer(powerballTextBuffer);
        } // Fl_Text_Display* powerball_number_view
        { ShowPowerballEntryWidget = new Fl_Button(440, 235, 120, 60, "Enter Powerball Numbers to play");
          ShowPowerballEntryWidget->color((Fl_Color)12);
          ShowPowerballEntryWidget->callback((Fl_Callback*)show_entry_window, (void*)(POWERBALL));
          ShowPowerballEntryWidget->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* ShowPowerballEntryWidget
        { ensurePowerball = new Fl_Check_Button(400, 145, 185, 60, "Ensure Powerball");
          ensurePowerball->down_box(FL_DOWN_BOX);
          ensurePowerball->callback((Fl_Callback*)cb_ensurePowerball);
          ensurePowerball->align(Fl_Align(132|FL_ALIGN_INSIDE));
        } // Fl_Check_Button* ensurePowerball
        { Fl_Button* o = new Fl_Button(515, 200, 140, 25, "Use Draw Results");
          o->callback((Fl_Callback*)use_draw_results, (void*)(R_POWERBALL));
        } // Fl_Button* o
        { p_draw = new Fl_Value_Input(395, 200, 120, 25);
        } // Fl_Value_Input* p_draw
        powerball_tab->end();
      } // Fl_Group* powerball_tab
      { lottostrike_tab = new Fl_Group(0, 145, 670, 475, "Lotto Strike");
        lottostrike_tab->box(FL_DOWN_BOX);
        lottostrike_tab->color((Fl_Color)11);
        lottostrike_tab->selection_color((Fl_Color)29);
        lottostrike_tab->labeltype(FL_EMBOSSED_LABEL);
        lottostrike_tab->hide();
        { Fl_Group* o = new Fl_Group(20, 165, 215, 50, "Lotto Strike Numbers");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)6);
          o->labelsize(16);
          { lsnum1 = new Fl_Value_Input(45, 175, 35, 30);
            lsnum1->color((Fl_Color)58);
            lsnum1->textsize(16);
            lsnum1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* lsnum1
          { lsnum2 = new Fl_Value_Input(85, 175, 35, 30);
            lsnum2->color((Fl_Color)58);
            lsnum2->textsize(16);
            lsnum2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* lsnum2
          { lsnum3 = new Fl_Value_Input(125, 175, 35, 30);
            lsnum3->color((Fl_Color)58);
            lsnum3->textsize(16);
            lsnum3->textcolor((Fl_Color)3);
          } // Fl_Value_Input* lsnum3
          { lsnum4 = new Fl_Value_Input(165, 175, 40, 30);
            lsnum4->color((Fl_Color)58);
            lsnum4->textsize(16);
            lsnum4->textcolor((Fl_Color)3);
          } // Fl_Value_Input* lsnum4
          o->end();
        } // Fl_Group* o
        { Fl_Text_Display* o = lottostrike_number_view = new Fl_Text_Display(15, 250, 410, 355, "Lotto Strike Numbers");
          lottostrike_number_view->box(FL_THIN_DOWN_BOX);
          lottostrike_number_view->color(FL_FOREGROUND_COLOR);
          lottostrike_number_view->selection_color(FL_FOREGROUND_COLOR);
          lottostrike_number_view->labeltype(FL_ENGRAVED_LABEL);
          lottostrike_number_view->labelsize(22);
          lottostrike_number_view->labelcolor((Fl_Color)80);
          lottostrike_number_view->textfont(13);
          lottostrike_number_view->textcolor((Fl_Color)2);
          Fl_Group::current()->resizable(lottostrike_number_view);
          o->buffer(lottostrikeTextBuffer);
        } // Fl_Text_Display* lottostrike_number_view
        { ShowLottostrikeEntryWidget = new Fl_Button(440, 235, 120, 60, "Enter numbers with form");
          ShowLottostrikeEntryWidget->color((Fl_Color)3);
          ShowLottostrikeEntryWidget->callback((Fl_Callback*)show_entry_window, (void*)(LOTTOSTRIKE));
          ShowLottostrikeEntryWidget->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* ShowLottostrikeEntryWidget
        lottostrike_tab->end();
        Fl_Group::current()->resizable(lottostrike_tab);
      } // Fl_Group* lottostrike_tab
      { setforlife_tab = new Fl_Group(0, 145, 670, 475, "Set for life");
        setforlife_tab->box(FL_DOWN_BOX);
        setforlife_tab->color(FL_CYAN);
        setforlife_tab->labeltype(FL_EMBOSSED_LABEL);
        setforlife_tab->hide();
        { Fl_Group* o = new Fl_Group(5, 170, 345, 45, "Set For Life Numbers");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)6);
          o->labelsize(16);
          { sfl_num1 = new Fl_Value_Input(20, 180, 35, 30);
            sfl_num1->color((Fl_Color)58);
            sfl_num1->textsize(16);
            sfl_num1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* sfl_num1
          { sfl_num2 = new Fl_Value_Input(60, 180, 35, 30);
            sfl_num2->color((Fl_Color)58);
            sfl_num2->textsize(16);
            sfl_num2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* sfl_num2
          { sfl_num3 = new Fl_Value_Input(100, 180, 35, 30);
            sfl_num3->color((Fl_Color)58);
            sfl_num3->textsize(16);
            sfl_num3->textcolor((Fl_Color)3);
          } // Fl_Value_Input* sfl_num3
          { sfl_num4 = new Fl_Value_Input(140, 180, 35, 30);
            sfl_num4->color((Fl_Color)58);
            sfl_num4->textsize(16);
            sfl_num4->textcolor((Fl_Color)3);
          } // Fl_Value_Input* sfl_num4
          { sfl_num5 = new Fl_Value_Input(180, 180, 35, 30);
            sfl_num5->color((Fl_Color)58);
            sfl_num5->textsize(16);
            sfl_num5->textcolor((Fl_Color)3);
          } // Fl_Value_Input* sfl_num5
          { sfl_num6 = new Fl_Value_Input(220, 180, 35, 30);
            sfl_num6->color((Fl_Color)58);
            sfl_num6->textsize(16);
            sfl_num6->textcolor((Fl_Color)3);
          } // Fl_Value_Input* sfl_num6
          { sfl_num7 = new Fl_Value_Input(260, 180, 35, 30);
            sfl_num7->color((Fl_Color)58);
            sfl_num7->textsize(16);
            sfl_num7->textcolor((Fl_Color)3);
          } // Fl_Value_Input* sfl_num7
          { sfl_num8 = new Fl_Value_Input(300, 180, 35, 30);
            sfl_num8->color((Fl_Color)58);
            sfl_num8->textsize(16);
            sfl_num8->textcolor((Fl_Color)3);
          } // Fl_Value_Input* sfl_num8
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(355, 170, 135, 45, "Bonus");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)222);
          o->labelsize(16);
          { sfl_bonus1 = new Fl_Value_Input(375, 180, 35, 30);
            sfl_bonus1->color((Fl_Color)59);
            sfl_bonus1->selection_color((Fl_Color)58);
            sfl_bonus1->labelcolor((Fl_Color)3);
            sfl_bonus1->textsize(16);
            sfl_bonus1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* sfl_bonus1
          { sfl_bonus2 = new Fl_Value_Input(415, 180, 35, 30);
            sfl_bonus2->color((Fl_Color)59);
            sfl_bonus2->selection_color((Fl_Color)58);
            sfl_bonus2->labelcolor((Fl_Color)3);
            sfl_bonus2->textsize(16);
            sfl_bonus2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* sfl_bonus2
          o->end();
        } // Fl_Group* o
        { Fl_Text_Display* o = sflnumber_view = new Fl_Text_Display(15, 250, 485, 355, "Set For Life Numbers");
          sflnumber_view->box(FL_THIN_DOWN_BOX);
          sflnumber_view->color(FL_FOREGROUND_COLOR);
          sflnumber_view->selection_color(FL_FOREGROUND_COLOR);
          sflnumber_view->labeltype(FL_ENGRAVED_LABEL);
          sflnumber_view->labelsize(22);
          sflnumber_view->labelcolor((Fl_Color)80);
          sflnumber_view->textfont(13);
          sflnumber_view->textcolor((Fl_Color)2);
          Fl_Group::current()->resizable(sflnumber_view);
          o->buffer(sflTextBuffer);
        } // Fl_Text_Display* sflnumber_view
        { ShowSFLEntryWidget = new Fl_Button(510, 235, 120, 60, "Enter numbers with form");
          ShowSFLEntryWidget->color((Fl_Color)219);
          ShowSFLEntryWidget->callback((Fl_Callback*)show_entry_window, (void*)(SET_FOR_LIFE));
          ShowSFLEntryWidget->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* ShowSFLEntryWidget
        { Fl_Button* o = new Fl_Button(510, 300, 120, 60, "Enter numbers with buttons");
          o->color((Fl_Color)219);
          o->callback((Fl_Callback*)cb_Enter2);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(510, 185, 140, 25, "Use Draw Results");
          o->callback((Fl_Callback*)use_draw_results, (void*)(R_SET_FOR_LIFE));
        } // Fl_Button* o
        { s_draw = new Fl_Value_Input(510, 160, 140, 25);
        } // Fl_Value_Input* s_draw
        setforlife_tab->end();
      } // Fl_Group* setforlife_tab
      tabular->end();
    } // Fl_Tabs* tabular
    { Fl_Menu_Button* o = new Fl_Menu_Button(170, 55, 160, 25, "Winning Divisions");
      o->color((Fl_Color)14);
      o->menu(menu_Winning);
    } // Fl_Menu_Button* o
    { Fl_Button* o = new Fl_Button(490, 55, 80, 25, "License");
      o->color((Fl_Color)14);
      o->selection_color((Fl_Color)6);
      o->callback((Fl_Callback*)cb_License);
    } // Fl_Button* o
    { new Fl_Box(170, 55, 90, 25);
    } // Fl_Box* o
    lotto_gui->end();
  } // Fl_Window* lotto_gui
  { results_window = new Fl_Double_Window(415, 380, "Results");
    results_window->color((Fl_Color)14);
    results_window->user_data((void*)(this));
    results_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Button* o = new Fl_Button(315, 350, 85, 25, "Close");
      o->color((Fl_Color)22);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
      o->labelcolor((Fl_Color)1);
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    { Fl_Box* o = new Fl_Box(0, 0, 415, 50, "RESULTS");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)137);
      o->labeltype(FL_SHADOW_LABEL);
      o->labelfont(1);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Text_Display* o = new Fl_Text_Display(5, 50, 410, 295);
      o->box(FL_DOWN_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->labelcolor((Fl_Color)2);
      o->textfont(13);
      o->textcolor((Fl_Color)2);
      o->buffer(textbuf_results);
    } // Fl_Text_Display* o
    { Fl_Button* o = new Fl_Button(15, 350, 85, 25, "Save");
      o->color((Fl_Color)22);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
      o->labelcolor((Fl_Color)1);
      o->callback((Fl_Callback*)cb_Save1);
    } // Fl_Button* o
    results_window->set_modal();
    results_window->end();
  } // Fl_Double_Window* results_window
  { divisions_window = new Fl_Double_Window(505, 295, "Tattslotto Divisions");
    divisions_window->color((Fl_Color)14);
    divisions_window->user_data((void*)(this));
    divisions_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Text_Display* o = new Fl_Text_Display(15, 70, 15, 20, "Division 1 : 6 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 100, 15, 20, "Division 2 : 5 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 130, 15, 20, "Division 3 : 5 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 160, 15, 20, "Division 4 : 4 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 190, 15, 20, "Division 5 : 3 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 220, 15, 20, "Division 6 : 1 number and 2 supplementaries");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Box* o = new Fl_Box(25, 10, 470, 40, "Tattslotto Winning Divisions");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(400, 255, 95, 30, "Close");
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    divisions_window->set_modal();
    divisions_window->end();
  } // Fl_Double_Window* divisions_window
  { help_window = new Fl_Double_Window(555, 440, "HELP / MANUAL");
    help_window->color((Fl_Color)14);
    help_window->user_data((void*)(this));
    help_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Box* o = new Fl_Box(15, 5, 535, 40, "HELP / MANUAL");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labeltype(FL_SHADOW_LABEL);
      o->labelfont(1);
      o->labelsize(26);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(230, 405, 85, 25, "Close");
      o->color((Fl_Color)22);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
      o->labelcolor((Fl_Color)1);
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    { helpView = new Fl_Help_View(15, 45, 535, 355);
      helpView->labelcolor((Fl_Color)18);
      loadHelp();
    } // Fl_Help_View* helpView
    help_window->end();
  } // Fl_Double_Window* help_window
  { oz_divisions_window = new Fl_Double_Window(495, 355, "OzLotto Divisions");
    oz_divisions_window->color((Fl_Color)14);
    oz_divisions_window->user_data((void*)(this));
    oz_divisions_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Text_Display* o = new Fl_Text_Display(15, 70, 15, 20, "Division 1 : 7 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 100, 15, 20, "Division 2 : 6 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 130, 15, 20, "Division 3 : 6 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 160, 15, 20, "Division 4 : 5 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 190, 15, 20, "Division 5 : 5 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 220, 15, 20, "Division 6 : 4 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 250, 15, 20, "Division 7 : 3 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Box* o = new Fl_Box(25, 10, 450, 40, "Ozlotto Winning Divisions");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(385, 295, 95, 30, "Close");
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    oz_divisions_window->set_modal();
    oz_divisions_window->end();
  } // Fl_Double_Window* oz_divisions_window
  { powerball_divisions_window = new Fl_Double_Window(480, 405, "Divisions");
    powerball_divisions_window->color((Fl_Color)14);
    powerball_divisions_window->user_data((void*)(this));
    powerball_divisions_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Box* o = new Fl_Box(0, 0, 480, 40, "Powerball Winning Divisions");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(190, 340, 95, 30, "Close");
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    { Fl_Text_Display* o = new Fl_Text_Display(25, 80, 15, 20, "Division 1 : 6 numbers and the powerball");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(25, 110, 15, 20, "Division 2 : 6 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(25, 140, 15, 20, "Division 3 : 5 numbers and the powerball");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(25, 170, 15, 20, "Division 4 : 5 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(25, 200, 15, 20, "Division 5 : 4 numbers and the powerball");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(25, 230, 15, 20, "Division 6 : 3 numbers and the powerball");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(25, 260, 15, 20, "Division 7 : 4 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(25, 290, 15, 20, "Division 8 : 2 numbers and the powerball");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    powerball_divisions_window->set_modal();
    powerball_divisions_window->end();
  } // Fl_Double_Window* powerball_divisions_window
  { TattsNumberEntryWindow = new Fl_Double_Window(430, 565, "Tattslotto Number");
    TattsNumberEntryWindow->color((Fl_Color)14);
    TattsNumberEntryWindow->user_data((void*)(this));
    { TattsEntryGroup = new Fl_Group(10, 20, 405, 510, "Enter Tattslotto Numbers");
      TattsEntryGroup->end();
    } // Fl_Group* TattsEntryGroup
    { Fl_Button* o = new Fl_Button(40, 535, 105, 20, "OK");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)cb_OK);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(305, 535, 105, 20, "Cancel");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    TattsNumberEntryWindow->end();
  } // Fl_Double_Window* TattsNumberEntryWindow
  { setforlife_divisions_window = new Fl_Double_Window(495, 375, "Divisions");
    setforlife_divisions_window->color((Fl_Color)14);
    setforlife_divisions_window->user_data((void*)(this));
    setforlife_divisions_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Text_Display* o = new Fl_Text_Display(15, 70, 15, 20, "Division 1 : 8 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 100, 15, 20, "Division 2 : 7 numbers and 1 bonus number");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 130, 15, 20, "Division 3 : 7 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 160, 15, 20, "Division 4 : 6 numbers and 1 or 2 bonus numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 190, 15, 20, "Division 5 : 6 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 220, 15, 20, "Division 6 : 5 numbers and 1 or 2 bonus numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 250, 15, 20, "Division 7 : 5 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Box* o = new Fl_Box(0, 0, 495, 40, "Set For Life Winning Divisions");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(165, 325, 95, 30, "Close");
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 280, 15, 20, "Division 8 : 4 numbers and 1 or 2 bonus numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    setforlife_divisions_window->set_modal();
    setforlife_divisions_window->end();
  } // Fl_Double_Window* setforlife_divisions_window
  { OzlottoNumberEntryWindow = new Fl_Double_Window(430, 565, "Ozlotto Number");
    OzlottoNumberEntryWindow->color((Fl_Color)14);
    OzlottoNumberEntryWindow->user_data((void*)(this));
    { OzlottoEntryGroup = new Fl_Group(10, 20, 410, 510, "Enter Ozlotto Numbers");
      OzlottoEntryGroup->end();
    } // Fl_Group* OzlottoEntryGroup
    { Fl_Button* o = new Fl_Button(25, 535, 105, 20, "OK");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)cb_OK1);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(305, 535, 105, 20, "Cancel");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    OzlottoNumberEntryWindow->end();
  } // Fl_Double_Window* OzlottoNumberEntryWindow
  { LottostrikeNumberEntryWindow = new Fl_Double_Window(430, 565, "Lotto Strike Number");
    LottostrikeNumberEntryWindow->color((Fl_Color)14);
    LottostrikeNumberEntryWindow->user_data((void*)(this));
    { LottostrikeEntryGroup = new Fl_Group(10, 20, 410, 510, "Enter Lotto Strike Numbers");
      LottostrikeEntryGroup->end();
    } // Fl_Group* LottostrikeEntryGroup
    { Fl_Button* o = new Fl_Button(25, 535, 105, 20, "OK");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)cb_OK2);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(305, 535, 105, 20, "Cancel");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    LottostrikeNumberEntryWindow->end();
  } // Fl_Double_Window* LottostrikeNumberEntryWindow
  { SetForLifeNumberEntryWindow = new Fl_Double_Window(430, 565, "Set For Life Number");
    SetForLifeNumberEntryWindow->color((Fl_Color)14);
    SetForLifeNumberEntryWindow->user_data((void*)(this));
    SetForLifeNumberEntryWindow->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { SetForLifeEntryGroup = new Fl_Group(10, 20, 405, 510, "Enter Set For Life Numbers");
      SetForLifeEntryGroup->end();
    } // Fl_Group* SetForLifeEntryGroup
    { Fl_Button* o = new Fl_Button(25, 535, 105, 20, "OK");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)cb_OK3);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(305, 535, 105, 20, "Cancel");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    SetForLifeNumberEntryWindow->end();
  } // Fl_Double_Window* SetForLifeNumberEntryWindow
  { Numberentry = new Fl_Double_Window(350, 250, "Number Entry");
    Numberentry->user_data((void*)(this));
    Numberentry->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { button_1 = new Fl_Light_Button(15, 25, 40, 25, "1");
      button_1->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(1));
    } // Fl_Light_Button* button_1
    { button_2 = new Fl_Light_Button(55, 25, 40, 25, "2");
      button_2->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(2));
    } // Fl_Light_Button* button_2
    { button_3 = new Fl_Light_Button(95, 25, 40, 25, "3");
      button_3->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(3));
    } // Fl_Light_Button* button_3
    { button_4 = new Fl_Light_Button(135, 25, 40, 25, "4");
      button_4->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(4));
    } // Fl_Light_Button* button_4
    { button_5 = new Fl_Light_Button(175, 25, 40, 25, "5");
      button_5->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(5));
    } // Fl_Light_Button* button_5
    { button_6 = new Fl_Light_Button(215, 25, 40, 25, "6");
      button_6->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(6));
    } // Fl_Light_Button* button_6
    { button_7 = new Fl_Light_Button(255, 25, 40, 25, "7");
      button_7->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(7));
    } // Fl_Light_Button* button_7
    { button_8 = new Fl_Light_Button(295, 25, 40, 25, "8");
      button_8->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(8));
    } // Fl_Light_Button* button_8
    { button_9 = new Fl_Light_Button(15, 50, 40, 25, "9");
      button_9->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(9));
    } // Fl_Light_Button* button_9
    { button_10 = new Fl_Light_Button(55, 50, 40, 25, "10");
      button_10->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(10));
    } // Fl_Light_Button* button_10
    { button_11 = new Fl_Light_Button(95, 50, 40, 25, "11");
      button_11->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(11));
    } // Fl_Light_Button* button_11
    { button_12 = new Fl_Light_Button(135, 50, 40, 25, "12");
      button_12->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(12));
    } // Fl_Light_Button* button_12
    { button_13 = new Fl_Light_Button(175, 50, 40, 25, "13");
      button_13->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(13));
    } // Fl_Light_Button* button_13
    { button_14 = new Fl_Light_Button(215, 50, 40, 25, "14");
      button_14->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(14));
    } // Fl_Light_Button* button_14
    { button_15 = new Fl_Light_Button(255, 50, 40, 25, "15");
      button_15->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(15));
    } // Fl_Light_Button* button_15
    { button_16 = new Fl_Light_Button(295, 50, 40, 25, "16");
      button_16->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(16));
    } // Fl_Light_Button* button_16
    { button_17 = new Fl_Light_Button(15, 75, 40, 25, "17");
      button_17->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(17));
    } // Fl_Light_Button* button_17
    { button_18 = new Fl_Light_Button(55, 75, 40, 25, "18");
      button_18->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(18));
    } // Fl_Light_Button* button_18
    { button_19 = new Fl_Light_Button(95, 75, 40, 25, "19");
      button_19->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(19));
    } // Fl_Light_Button* button_19
    { button_20 = new Fl_Light_Button(135, 75, 40, 25, "20");
      button_20->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(20));
    } // Fl_Light_Button* button_20
    { button_21 = new Fl_Light_Button(175, 75, 40, 25, "21");
      button_21->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(21));
    } // Fl_Light_Button* button_21
    { button_22 = new Fl_Light_Button(215, 75, 40, 25, "22");
      button_22->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(22));
    } // Fl_Light_Button* button_22
    { button_23 = new Fl_Light_Button(255, 75, 40, 25, "23");
      button_23->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(23));
    } // Fl_Light_Button* button_23
    { button_24 = new Fl_Light_Button(295, 75, 40, 25, "24");
      button_24->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(24));
    } // Fl_Light_Button* button_24
    { button_25 = new Fl_Light_Button(15, 100, 40, 25, "25");
      button_25->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(25));
    } // Fl_Light_Button* button_25
    { button_26 = new Fl_Light_Button(55, 100, 40, 25, "26");
      button_26->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(26));
    } // Fl_Light_Button* button_26
    { button_27 = new Fl_Light_Button(95, 100, 40, 25, "27");
      button_27->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(27));
    } // Fl_Light_Button* button_27
    { button_28 = new Fl_Light_Button(135, 100, 40, 25, "28");
      button_28->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(28));
    } // Fl_Light_Button* button_28
    { button_29 = new Fl_Light_Button(175, 100, 40, 25, "29");
      button_29->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(29));
    } // Fl_Light_Button* button_29
    { button_30 = new Fl_Light_Button(215, 100, 40, 25, "30");
      button_30->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(30));
    } // Fl_Light_Button* button_30
    { button_31 = new Fl_Light_Button(255, 100, 40, 25, "31");
      button_31->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(31));
    } // Fl_Light_Button* button_31
    { button_32 = new Fl_Light_Button(295, 100, 40, 25, "32");
      button_32->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(32));
    } // Fl_Light_Button* button_32
    { button_33 = new Fl_Light_Button(15, 125, 40, 25, "33");
      button_33->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(33));
    } // Fl_Light_Button* button_33
    { button_34 = new Fl_Light_Button(55, 125, 40, 25, "34");
      button_34->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(34));
    } // Fl_Light_Button* button_34
    { button_35 = new Fl_Light_Button(95, 125, 40, 25, "35");
      button_35->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(35));
    } // Fl_Light_Button* button_35
    { button_36 = new Fl_Light_Button(135, 125, 40, 25, "36");
      button_36->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(36));
    } // Fl_Light_Button* button_36
    { button_37 = new Fl_Light_Button(175, 125, 40, 25, "37");
      button_37->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(37));
    } // Fl_Light_Button* button_37
    { button_38 = new Fl_Light_Button(215, 125, 40, 25, "38");
      button_38->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(38));
    } // Fl_Light_Button* button_38
    { button_39 = new Fl_Light_Button(255, 125, 40, 25, "39");
      button_39->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(39));
    } // Fl_Light_Button* button_39
    { button_40 = new Fl_Light_Button(295, 125, 40, 25, "40");
      button_40->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(40));
    } // Fl_Light_Button* button_40
    { button_41 = new Fl_Light_Button(15, 150, 40, 25, "41");
      button_41->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(41));
    } // Fl_Light_Button* button_41
    { button_42 = new Fl_Light_Button(55, 150, 40, 25, "42");
      button_42->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(42));
    } // Fl_Light_Button* button_42
    { button_43 = new Fl_Light_Button(95, 150, 40, 25, "43");
      button_43->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(43));
    } // Fl_Light_Button* button_43
    { button_44 = new Fl_Light_Button(135, 150, 40, 25, "44");
      button_44->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(44));
    } // Fl_Light_Button* button_44
    { button_45 = new Fl_Light_Button(175, 150, 40, 25, "45");
      button_45->callback((Fl_Callback*)NumberSelectorUpdate_cb, (void*)(45));
    } // Fl_Light_Button* button_45
    { Fl_Button* o = new Fl_Button(40, 210, 60, 30, "OK");
      o->labeltype(FL_EMBOSSED_LABEL);
      o->callback((Fl_Callback*)cb_OK4);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(255, 210, 60, 30, "Cancel");
      o->labeltype(FL_EMBOSSED_LABEL);
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    Numberentry->end();
  } // Fl_Double_Window* Numberentry
  { PowerballNumberEntryWindow = new Fl_Double_Window(430, 565, "Powerball Number");
    PowerballNumberEntryWindow->color((Fl_Color)14);
    PowerballNumberEntryWindow->user_data((void*)(this));
    PowerballNumberEntryWindow->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { PowerballEntryGroup = new Fl_Group(10, 20, 405, 510, "Enter Powerball Numbers");
      PowerballEntryGroup->end();
    } // Fl_Group* PowerballEntryGroup
    { Fl_Button* o = new Fl_Button(25, 535, 105, 20, "OK");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)cb_OK5);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(305, 535, 105, 20, "Cancel");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    PowerballNumberEntryWindow->end();
  } // Fl_Double_Window* PowerballNumberEntryWindow
  { lottostrike_divisions_window = new Fl_Double_Window(490, 240, "Lotto Strike Divisions");
    lottostrike_divisions_window->color((Fl_Color)14);
    lottostrike_divisions_window->user_data((void*)(this));
    lottostrike_divisions_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Text_Display* o = new Fl_Text_Display(15, 70, 15, 20, "Division 1 : All 4 of the 1st four numbers in order");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 100, 15, 20, "Division 2 : 3 of the first four numbers in order");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 130, 15, 20, "Division 3 : 2 of the first 4 numbers in order");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 160, 15, 20, "Division 4 : 1 of the first 4 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Box* o = new Fl_Box(25, 10, 445, 40, "Lotto Strike Winning Divisions");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(360, 190, 95, 35, "Close");
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    lottostrike_divisions_window->set_modal();
    lottostrike_divisions_window->end();
  } // Fl_Double_Window* lottostrike_divisions_window
  { LicenseWindow = new Fl_Double_Window(590, 570, "License");
    LicenseWindow->color((Fl_Color)14);
    LicenseWindow->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(0, 0, 590, 55, "License");
      o->box(FL_ENGRAVED_BOX);
      o->color(FL_SELECTION_COLOR);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(36);
      o->labelcolor((Fl_Color)6);
    } // Fl_Box* o
    { Fl_Text_Display* o = new Fl_Text_Display(0, 55, 585, 465);
      o->box(FL_DOWN_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->labelfont(13);
      o->labelsize(10);
      o->textfont(13);
      o->textsize(12);
      o->textcolor((Fl_Color)6);
      o->align(Fl_Align(129));
      o->buffer(licenseTextBuffer);
    } // Fl_Text_Display* o
    { Fl_Button* o = new Fl_Button(250, 540, 145, 25, "Close");
      o->color((Fl_Color)31);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    { Fl_Box* o = new Fl_Box(0, 520, 265, 20, "(C) Dennis Katsonis   2014");
      o->labelfont(14);
    } // Fl_Box* o
    LicenseWindow->end();
  } // Fl_Double_Window* LicenseWindow
  return LicenseWindow;
}

int UserInterface::quit() {
  this->lotto_gui->hide();
  this->divisions_window->hide();
  this->results_window->hide();
  this->TattsNumberEntryWindow->hide();;
  return 0;
  // Closes the program by hiding the main gui.  Hiding the main window ends the 
  // execution loop.
}

void UserInterface::show_help_window() {
  this->help_window->show();
}

void UserInterface::NumberSelectorUpdate_cb(Fl_Widget* w, void* userdata) {
  Fl_Widget *p = w->parent();
  while (p->parent()) p = p->parent();
  int ptr = *((int*)(&userdata));
  ((UserInterface*)p->user_data())->NumberSelectorUpdate(ptr);
}

void UserInterface::show_Numberentry_window() {
  this->Numberentry->show();
}

void UserInterface::show_license_window() {
  this->LicenseWindow->show();
}

void UserInterface::show_divisions(Fl_Widget* w, void* userdata) {
  Fl_Widget *p = w->parent();
  while (p->parent()) p = p->parent();
  
  ((UserInterface*)p->user_data())->show_div_callback(w, userdata);
}

void UserInterface::show_div_callback(Fl_Widget* w, void* userdata) {
  if (userdata == (gameType*)LOTTOSTRIKE) {
  	this->lottostrike_divisions_window->show();
  } else if (userdata == (gameType*)OZLOTTO) {
  	oz_divisions_window->show();
  } else if (userdata == (gameType*)TATTSLOTTO) {
  	divisions_window->show();
  } else if (userdata == (gameType*)POWERBALL) {
  	powerball_divisions_window->show();
  } else if (userdata == (gameType*)SET_FOR_LIFE) {
  	setforlife_divisions_window->show();
  }
}

void UserInterface::hide_parent(Fl_Widget *w, void* data) {
  (w->parent())->hide();
}

void UserInterface::show_entry_window(Fl_Widget* w, void* userdata) {
  Fl_Widget *p = w->parent();
  while (p->parent()) p = p->parent();
  
  ((UserInterface*)p->user_data())->show_entry_callback(w, userdata);
}

void UserInterface::use_draw_results(Fl_Widget* w, void* userdata) {
  Fl_Widget *p = w->parent();
  while (p->parent()) p = p->parent();
  
  ((UserInterface*)p->user_data())->use_draw_results_cb(w, userdata);
}
