// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "AussieLottoGUI.h"
/* Aussie Lotto */
#include <iostream>
#include <Fl/fl_ask.h>

void UserInterface::cb_Quit_i(Fl_Button*, void*) {
  quit();
}
void UserInterface::cb_Quit(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Quit_i(o,v);
}

void UserInterface::cb_Open_i(Fl_Menu_*, void*) {
  open_file();
}
void UserInterface::cb_Open(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Open_i(o,v);
}

void UserInterface::cb_Save_i(Fl_Menu_*, void*) {
  save_file();
}
void UserInterface::cb_Save(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Save_i(o,v);
}

void UserInterface::cb_Exit_i(Fl_Menu_*, void*) {
  quit();
}
void UserInterface::cb_Exit(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Exit_i(o,v);
}

Fl_Menu_Item UserInterface::menu_File[] = {
 {"Open", 0,  (Fl_Callback*)UserInterface::cb_Open, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save", 0,  (Fl_Callback*)UserInterface::cb_Save, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Exit", 0,  (Fl_Callback*)UserInterface::cb_Exit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void UserInterface::cb_About_i(Fl_Button*, void*) {
  fl_message("Aussie Lotto\nWritten by Dennis Katsonis, April 2014.\nVersion " PROG_VERSION"\nBuild date : "__DATE__ "  " __TIME__"\n(C) Dennis Katsonis 2014\nLicensed under the GPL3.  See 'License' for more details");
}
void UserInterface::cb_About(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_About_i(o,v);
}

void UserInterface::cb_Generate_i(Fl_Button*, void*) {
  generate();
}
void UserInterface::cb_Generate(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Generate_i(o,v);
}

void UserInterface::cb_Check_i(Fl_Button*, void*) {
  check_lotto();
}
void UserInterface::cb_Check(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Check_i(o,v);
}

void UserInterface::cb_Check1_i(Fl_Menu_*, void*) {
  check_lotto();
}
void UserInterface::cb_Check1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Check1_i(o,v);
}

void UserInterface::cb_Generate1_i(Fl_Menu_*, void*) {
  generate();
}
void UserInterface::cb_Generate1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Generate1_i(o,v);
}

void UserInterface::cb_Clear_i(Fl_Menu_*, void*) {
  clear_lotto();
}
void UserInterface::cb_Clear(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Clear_i(o,v);
}

void UserInterface::cb_Clear1_i(Fl_Menu_*, void*) {
  clear_results();
}
void UserInterface::cb_Clear1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Clear1_i(o,v);
}

Fl_Menu_Item UserInterface::menu_Options[] = {
 {"Check", 0,  (Fl_Callback*)UserInterface::cb_Check1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Generate", 0,  (Fl_Callback*)UserInterface::cb_Generate1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Clear Numbers", 0,  (Fl_Callback*)UserInterface::cb_Clear, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Clear Lottery Results", 0,  (Fl_Callback*)UserInterface::cb_Clear1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void UserInterface::cb_Help_i(Fl_Button*, void*) {
  show_help_window();
}
void UserInterface::cb_Help(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Help_i(o,v);
}

void UserInterface::cb_tabular_i(Fl_Tabs*, void*) {
  changeTab();
}
void UserInterface::cb_tabular(Fl_Tabs* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_tabular_i(o,v);
}

void UserInterface::cb_ShowTattsEntryWidget_i(Fl_Button*, void*) {
  show_tatts_entry_window();
}
void UserInterface::cb_ShowTattsEntryWidget(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_ShowTattsEntryWidget_i(o,v);
}

void UserInterface::cb_Enter_i(Fl_Button*, void*) {
  show_Numberentry_window();
}
void UserInterface::cb_Enter(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_Enter_i(o,v);
}

void UserInterface::cb_ShowOzlottoEntryWidget_i(Fl_Button*, void*) {
  show_ozlotto_entry_window();
}
void UserInterface::cb_ShowOzlottoEntryWidget(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_ShowOzlottoEntryWidget_i(o,v);
}

void UserInterface::cb_Enter1_i(Fl_Button*, void*) {
  show_Numberentry_window();
}
void UserInterface::cb_Enter1(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_Enter1_i(o,v);
}

void UserInterface::cb_ShowPowerballEntryWidget_i(Fl_Button*, void*) {
  show_powerball_entry_window();
}
void UserInterface::cb_ShowPowerballEntryWidget(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_ShowPowerballEntryWidget_i(o,v);
}

void UserInterface::cb_ensurePowerball_i(Fl_Check_Button*, void*) {
  ensurePowerballButton();
}
void UserInterface::cb_ensurePowerball(Fl_Check_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_ensurePowerball_i(o,v);
}

void UserInterface::cb_ShowLottostrikeEntryWidget_i(Fl_Button*, void*) {
  show_lottostrike_entry_window();
}
void UserInterface::cb_ShowLottostrikeEntryWidget(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->parent()->user_data()))->cb_ShowLottostrikeEntryWidget_i(o,v);
}

void UserInterface::cb_Tattslotto_i(Fl_Menu_*, void*) {
  show_tatts_divisions_window();
}
void UserInterface::cb_Tattslotto(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Tattslotto_i(o,v);
}

void UserInterface::cb_Oz_i(Fl_Menu_*, void*) {
  show_oz_divisions_window();
}
void UserInterface::cb_Oz(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Oz_i(o,v);
}

void UserInterface::cb_Powerball_i(Fl_Menu_*, void*) {
  show_powerball_divisions_window();
}
void UserInterface::cb_Powerball(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Powerball_i(o,v);
}

void UserInterface::cb_Lotto_i(Fl_Menu_*, void*) {
  show_lottostrike_divisions_window();
}
void UserInterface::cb_Lotto(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Lotto_i(o,v);
}

Fl_Menu_Item UserInterface::menu_Winning[] = {
 {"Tattslotto", 0,  (Fl_Callback*)UserInterface::cb_Tattslotto, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Oz Lotto", 0,  (Fl_Callback*)UserInterface::cb_Oz, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Powerball", 0,  (Fl_Callback*)UserInterface::cb_Powerball, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Lotto Strike", 0,  (Fl_Callback*)UserInterface::cb_Lotto, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void UserInterface::cb_License_i(Fl_Button*, void*) {
  show_license_window();
}
void UserInterface::cb_License(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_License_i(o,v);
}

void UserInterface::cb_Close_i(Fl_Button*, void*) {
  close_results_window();
}
void UserInterface::cb_Close(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Close_i(o,v);
}

void UserInterface::cb_Save1_i(Fl_Button*, void*) {
  saveResults();
}
void UserInterface::cb_Save1(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Save1_i(o,v);
}

void UserInterface::cb_Close1_i(Fl_Button*, void*) {
  close_tatts_divisions_window();
}
void UserInterface::cb_Close1(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Close1_i(o,v);
}

void UserInterface::cb_Close2_i(Fl_Button*, void*) {
  close_help_window();
}
void UserInterface::cb_Close2(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Close2_i(o,v);
}

void UserInterface::cb_Close3_i(Fl_Button*, void*) {
  close_oz_divisions_window();
}
void UserInterface::cb_Close3(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Close3_i(o,v);
}

void UserInterface::cb_Close4_i(Fl_Button*, void*) {
  close_powerball_divisions_window();
}
void UserInterface::cb_Close4(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Close4_i(o,v);
}

void UserInterface::cb_OK_i(Fl_Button*, void*) {
  tattsEntry();
}
void UserInterface::cb_OK(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_OK_i(o,v);
}

void UserInterface::cb_Cancel_i(Fl_Button*, void*) {
  hide_tatts_entry_window();
}
void UserInterface::cb_Cancel(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Cancel_i(o,v);
}

void UserInterface::cb_OK1_i(Fl_Button*, void*) {
  ozlottoEntry();
}
void UserInterface::cb_OK1(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_OK1_i(o,v);
}

void UserInterface::cb_Cancel1_i(Fl_Button*, void*) {
  hide_ozlotto_entry_window();
}
void UserInterface::cb_Cancel1(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Cancel1_i(o,v);
}

void UserInterface::cb_OK2_i(Fl_Button*, void*) {
  lottostrikeEntry();
}
void UserInterface::cb_OK2(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_OK2_i(o,v);
}

void UserInterface::cb_Cancel2_i(Fl_Button*, void*) {
  hide_lottostrike_entry_window();
}
void UserInterface::cb_Cancel2(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Cancel2_i(o,v);
}

void UserInterface::cb_button_1_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(1);
}
void UserInterface::cb_button_1(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_1_i(o,v);
}

void UserInterface::cb_button_2_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(2);
}
void UserInterface::cb_button_2(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_2_i(o,v);
}

void UserInterface::cb_button_3_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(3);
}
void UserInterface::cb_button_3(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_3_i(o,v);
}

void UserInterface::cb_button_4_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(4);
}
void UserInterface::cb_button_4(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_4_i(o,v);
}

void UserInterface::cb_button_5_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(5);
}
void UserInterface::cb_button_5(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_5_i(o,v);
}

void UserInterface::cb_button_6_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(6);
}
void UserInterface::cb_button_6(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_6_i(o,v);
}

void UserInterface::cb_button_7_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(7);
}
void UserInterface::cb_button_7(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_7_i(o,v);
}

void UserInterface::cb_button_8_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(8);
}
void UserInterface::cb_button_8(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_8_i(o,v);
}

void UserInterface::cb_button_9_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(9);
}
void UserInterface::cb_button_9(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_9_i(o,v);
}

void UserInterface::cb_button_10_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(10);
}
void UserInterface::cb_button_10(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_10_i(o,v);
}

void UserInterface::cb_button_11_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(11);
}
void UserInterface::cb_button_11(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_11_i(o,v);
}

void UserInterface::cb_button_12_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(12);
}
void UserInterface::cb_button_12(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_12_i(o,v);
}

void UserInterface::cb_button_13_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(13);
}
void UserInterface::cb_button_13(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_13_i(o,v);
}

void UserInterface::cb_button_14_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(14);
}
void UserInterface::cb_button_14(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_14_i(o,v);
}

void UserInterface::cb_button_15_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(15);
}
void UserInterface::cb_button_15(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_15_i(o,v);
}

void UserInterface::cb_button_16_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(16);
}
void UserInterface::cb_button_16(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_16_i(o,v);
}

void UserInterface::cb_button_17_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(17);
}
void UserInterface::cb_button_17(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_17_i(o,v);
}

void UserInterface::cb_button_18_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(18);
}
void UserInterface::cb_button_18(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_18_i(o,v);
}

void UserInterface::cb_button_19_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(19);
}
void UserInterface::cb_button_19(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_19_i(o,v);
}

void UserInterface::cb_button_20_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(20);
}
void UserInterface::cb_button_20(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_20_i(o,v);
}

void UserInterface::cb_button_21_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(21);
}
void UserInterface::cb_button_21(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_21_i(o,v);
}

void UserInterface::cb_button_22_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(22);
}
void UserInterface::cb_button_22(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_22_i(o,v);
}

void UserInterface::cb_button_23_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(23);
}
void UserInterface::cb_button_23(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_23_i(o,v);
}

void UserInterface::cb_button_24_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(24);
}
void UserInterface::cb_button_24(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_24_i(o,v);
}

void UserInterface::cb_button_25_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(25);
}
void UserInterface::cb_button_25(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_25_i(o,v);
}

void UserInterface::cb_button_26_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(26);
}
void UserInterface::cb_button_26(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_26_i(o,v);
}

void UserInterface::cb_button_27_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(27);
}
void UserInterface::cb_button_27(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_27_i(o,v);
}

void UserInterface::cb_button_28_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(28);
}
void UserInterface::cb_button_28(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_28_i(o,v);
}

void UserInterface::cb_button_29_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(29);
}
void UserInterface::cb_button_29(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_29_i(o,v);
}

void UserInterface::cb_button_30_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(30);
}
void UserInterface::cb_button_30(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_30_i(o,v);
}

void UserInterface::cb_button_31_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(31);
}
void UserInterface::cb_button_31(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_31_i(o,v);
}

void UserInterface::cb_button_32_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(32);
}
void UserInterface::cb_button_32(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_32_i(o,v);
}

void UserInterface::cb_button_33_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(33);
}
void UserInterface::cb_button_33(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_33_i(o,v);
}

void UserInterface::cb_button_34_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(34);
}
void UserInterface::cb_button_34(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_34_i(o,v);
}

void UserInterface::cb_button_35_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(35);
}
void UserInterface::cb_button_35(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_35_i(o,v);
}

void UserInterface::cb_button_36_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(36);
}
void UserInterface::cb_button_36(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_36_i(o,v);
}

void UserInterface::cb_button_37_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(37);
}
void UserInterface::cb_button_37(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_37_i(o,v);
}

void UserInterface::cb_button_38_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(38);
}
void UserInterface::cb_button_38(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_38_i(o,v);
}

void UserInterface::cb_button_39_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(39);
}
void UserInterface::cb_button_39(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_39_i(o,v);
}

void UserInterface::cb_button_40_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(40);
}
void UserInterface::cb_button_40(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_40_i(o,v);
}

void UserInterface::cb_button_41_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(41);
}
void UserInterface::cb_button_41(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_41_i(o,v);
}

void UserInterface::cb_button_42_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(42);
}
void UserInterface::cb_button_42(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_42_i(o,v);
}

void UserInterface::cb_button_43_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(43);
}
void UserInterface::cb_button_43(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_43_i(o,v);
}

void UserInterface::cb_button_44_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(44);
}
void UserInterface::cb_button_44(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_44_i(o,v);
}

void UserInterface::cb_button_45_i(Fl_Light_Button*, void*) {
  NumberSelectorUpdate(45);
}
void UserInterface::cb_button_45(Fl_Light_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_button_45_i(o,v);
}

void UserInterface::cb_OK3_i(Fl_Button*, void*) {
  submitButtonNums();
}
void UserInterface::cb_OK3(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_OK3_i(o,v);
}

void UserInterface::cb_Cancel3_i(Fl_Button*, void*) {
  hide_Numberentry_window();
}
void UserInterface::cb_Cancel3(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Cancel3_i(o,v);
}

void UserInterface::cb_OK4_i(Fl_Button*, void*) {
  powerballEntry();
}
void UserInterface::cb_OK4(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_OK4_i(o,v);
}

void UserInterface::cb_Cancel4_i(Fl_Button*, void*) {
  hide_powerball_entry_window();
}
void UserInterface::cb_Cancel4(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Cancel4_i(o,v);
}

void UserInterface::cb_Close5_i(Fl_Button*, void*) {
  close_lottostrike_divisions_window();
}
void UserInterface::cb_Close5(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Close5_i(o,v);
}

void UserInterface::cb_Close6_i(Fl_Button*, void*) {
  close_license_window();
}
void UserInterface::cb_Close6(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Close6_i(o,v);
}

Fl_Window* UserInterface::make_window() {
  { lotto_gui = new Fl_Window(605, 620, "Aussie Lotto");
    lotto_gui->color((Fl_Color)14);
    lotto_gui->selection_color(FL_GRAY0);
    lotto_gui->labelcolor((Fl_Color)12);
    lotto_gui->user_data((void*)(this));
    lotto_gui->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    lotto_gui->when(FL_WHEN_RELEASE_ALWAYS);
    { Fl_Box* o = new Fl_Box(0, 0, 605, 40, "Aussie Lotto");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->selection_color(FL_BACKGROUND2_COLOR);
      o->labeltype(FL_SHADOW_LABEL);
      o->labelfont(14);
      o->labelsize(26);
      o->labelcolor((Fl_Color)1);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(540, 55, 65, 25, "Quit");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)cb_Quit);
    } // Fl_Button* o
    { Fl_Menu_Button* o = new Fl_Menu_Button(5, 55, 75, 25, "File");
      o->color((Fl_Color)14);
      o->menu(menu_File);
    } // Fl_Menu_Button* o
    { Fl_Button* o = new Fl_Button(395, 55, 65, 25, "About");
      o->color((Fl_Color)14);
      o->selection_color((Fl_Color)6);
      o->callback((Fl_Callback*)cb_About);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(5, 85, 125, 35, "Generate Numbers");
      o->color((Fl_Color)137);
      o->selection_color(FL_FOREGROUND_COLOR);
      o->labelfont(1);
      o->labelcolor(FL_RED);
      o->callback((Fl_Callback*)cb_Generate);
      o->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(135, 85, 135, 35, "Check Numbers");
      o->color((Fl_Color)138);
      o->selection_color(FL_FOREGROUND_COLOR);
      o->labelfont(1);
      o->labelcolor(FL_RED);
      o->callback((Fl_Callback*)cb_Check);
      o->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* o
    { num_games = new Fl_Value_Input(460, 85, 95, 30, "Number of Games");
      num_games->color(FL_FOREGROUND_COLOR);
      num_games->textfont(1);
      num_games->textsize(16);
      num_games->textcolor((Fl_Color)3);
    } // Fl_Value_Input* num_games
    { Fl_Menu_Button* o = new Fl_Menu_Button(80, 55, 90, 25, "Options");
      o->color((Fl_Color)14);
      o->menu(menu_Options);
    } // Fl_Menu_Button* o
    { Fl_Button* o = new Fl_Button(330, 55, 65, 25, "Help");
      o->color((Fl_Color)14);
      o->callback((Fl_Callback*)cb_Help);
    } // Fl_Button* o
    { tabular = new Fl_Tabs(0, 125, 565, 605);
      tabular->box(FL_THIN_DOWN_BOX);
      tabular->labeltype(FL_NO_LABEL);
      tabular->callback((Fl_Callback*)cb_tabular);
      tabular->align(Fl_Align(37));
      { tattslotto_tab = new Fl_Group(0, 150, 565, 470, "Tattslotto/Gold Lotto/X Lotto");
        tattslotto_tab->box(FL_DOWN_BOX);
        tattslotto_tab->color(FL_DARK_CYAN);
        tattslotto_tab->selection_color((Fl_Color)29);
        tattslotto_tab->labeltype(FL_EMBOSSED_LABEL);
        { Fl_Group* o = new Fl_Group(20, 170, 280, 45, "Lottery Numbers");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)6);
          o->labelsize(16);
          { num1 = new Fl_Value_Input(45, 180, 35, 30);
            num1->color((Fl_Color)58);
            num1->textsize(16);
            num1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num1
          { num2 = new Fl_Value_Input(85, 180, 35, 30);
            num2->color((Fl_Color)58);
            num2->textsize(16);
            num2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num2
          { num3 = new Fl_Value_Input(125, 180, 35, 30);
            num3->color((Fl_Color)58);
            num3->textsize(16);
            num3->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num3
          { num4 = new Fl_Value_Input(165, 180, 35, 30);
            num4->color((Fl_Color)58);
            num4->textsize(16);
            num4->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num4
          { num5 = new Fl_Value_Input(205, 180, 35, 30);
            num5->color((Fl_Color)58);
            num5->textsize(16);
            num5->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num5
          { num6 = new Fl_Value_Input(245, 180, 35, 30);
            num6->color((Fl_Color)58);
            num6->textsize(16);
            num6->textcolor((Fl_Color)3);
          } // Fl_Value_Input* num6
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(315, 170, 135, 45, "Supplementaries");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)222);
          o->labelsize(16);
          { supp1 = new Fl_Value_Input(335, 180, 35, 30);
            supp1->color((Fl_Color)59);
            supp1->selection_color((Fl_Color)58);
            supp1->labelcolor((Fl_Color)3);
            supp1->textsize(16);
            supp1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* supp1
          { supp2 = new Fl_Value_Input(375, 180, 35, 30);
            supp2->color((Fl_Color)59);
            supp2->selection_color((Fl_Color)58);
            supp2->labelcolor((Fl_Color)3);
            supp2->textsize(16);
            supp2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* supp2
          o->end();
        } // Fl_Group* o
        { Fl_Text_Display* o = number_view = new Fl_Text_Display(15, 250, 410, 355, "Lottery Numbers");
          number_view->box(FL_THIN_DOWN_BOX);
          number_view->color(FL_FOREGROUND_COLOR);
          number_view->selection_color(FL_FOREGROUND_COLOR);
          number_view->labeltype(FL_ENGRAVED_LABEL);
          number_view->labelsize(22);
          number_view->labelcolor((Fl_Color)80);
          number_view->textfont(13);
          number_view->textcolor((Fl_Color)2);
          o->buffer(tattslottoTextBuffer);
        } // Fl_Text_Display* number_view
        { ShowTattsEntryWidget = new Fl_Button(440, 235, 120, 60, "Enter numbers with form");
          ShowTattsEntryWidget->color((Fl_Color)14);
          ShowTattsEntryWidget->callback((Fl_Callback*)cb_ShowTattsEntryWidget);
          ShowTattsEntryWidget->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* ShowTattsEntryWidget
        { Fl_Button* o = new Fl_Button(440, 305, 120, 60, "Enter numbers with buttons");
          o->color((Fl_Color)14);
          o->callback((Fl_Callback*)cb_Enter);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* o
        tattslotto_tab->end();
      } // Fl_Group* tattslotto_tab
      { ozlotto_tab = new Fl_Group(0, 150, 565, 470, "OzLotto");
        ozlotto_tab->box(FL_DOWN_BOX);
        ozlotto_tab->color(FL_DARK_GREEN);
        ozlotto_tab->labeltype(FL_EMBOSSED_LABEL);
        ozlotto_tab->hide();
        { Fl_Group* o = new Fl_Group(20, 170, 335, 45, "Oz Lotto Numbers");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)6);
          o->labelsize(16);
          { oz_num1 = new Fl_Value_Input(45, 180, 35, 30);
            oz_num1->color((Fl_Color)58);
            oz_num1->textsize(16);
            oz_num1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num1
          { oz_num2 = new Fl_Value_Input(85, 180, 35, 30);
            oz_num2->color((Fl_Color)58);
            oz_num2->textsize(16);
            oz_num2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num2
          { oz_num3 = new Fl_Value_Input(125, 180, 35, 30);
            oz_num3->color((Fl_Color)58);
            oz_num3->textsize(16);
            oz_num3->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num3
          { oz_num4 = new Fl_Value_Input(165, 180, 35, 30);
            oz_num4->color((Fl_Color)58);
            oz_num4->textsize(16);
            oz_num4->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num4
          { oz_num5 = new Fl_Value_Input(205, 180, 35, 30);
            oz_num5->color((Fl_Color)58);
            oz_num5->textsize(16);
            oz_num5->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num5
          { oz_num6 = new Fl_Value_Input(245, 180, 35, 30);
            oz_num6->color((Fl_Color)58);
            oz_num6->textsize(16);
            oz_num6->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num6
          { oz_num7 = new Fl_Value_Input(285, 180, 35, 30);
            oz_num7->color((Fl_Color)58);
            oz_num7->textsize(16);
            oz_num7->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_num7
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(375, 170, 125, 45, "Supplementaries");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)222);
          o->labelsize(16);
          { oz_supp1 = new Fl_Value_Input(395, 180, 35, 30);
            oz_supp1->color((Fl_Color)59);
            oz_supp1->selection_color((Fl_Color)58);
            oz_supp1->labelcolor((Fl_Color)3);
            oz_supp1->textsize(16);
            oz_supp1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_supp1
          { oz_supp2 = new Fl_Value_Input(435, 180, 35, 30);
            oz_supp2->color((Fl_Color)59);
            oz_supp2->selection_color((Fl_Color)58);
            oz_supp2->labelcolor((Fl_Color)3);
            oz_supp2->textsize(16);
            oz_supp2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* oz_supp2
          o->end();
        } // Fl_Group* o
        { Fl_Text_Display* o = oz_number_view = new Fl_Text_Display(15, 250, 410, 355, "Oz Lotto Numbers");
          oz_number_view->box(FL_THIN_DOWN_BOX);
          oz_number_view->color(FL_FOREGROUND_COLOR);
          oz_number_view->selection_color(FL_FOREGROUND_COLOR);
          oz_number_view->labeltype(FL_ENGRAVED_LABEL);
          oz_number_view->labelsize(22);
          oz_number_view->labelcolor((Fl_Color)80);
          oz_number_view->textfont(13);
          oz_number_view->textcolor((Fl_Color)2);
          Fl_Group::current()->resizable(oz_number_view);
          o->buffer(ozlottoTextBuffer);
        } // Fl_Text_Display* oz_number_view
        { ShowOzlottoEntryWidget = new Fl_Button(440, 235, 120, 60, "Enter numbers with form");
          ShowOzlottoEntryWidget->color((Fl_Color)10);
          ShowOzlottoEntryWidget->callback((Fl_Callback*)cb_ShowOzlottoEntryWidget);
          ShowOzlottoEntryWidget->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* ShowOzlottoEntryWidget
        { Fl_Button* o = new Fl_Button(440, 305, 120, 60, "Enter numbers with buttons");
          o->color((Fl_Color)10);
          o->callback((Fl_Callback*)cb_Enter1);
          o->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* o
        ozlotto_tab->end();
      } // Fl_Group* ozlotto_tab
      { powerball_tab = new Fl_Group(0, 150, 565, 580, "Powerball");
        powerball_tab->box(FL_DOWN_BOX);
        powerball_tab->color((Fl_Color)187);
        powerball_tab->labeltype(FL_EMBOSSED_LABEL);
        powerball_tab->hide();
        { Fl_Group* o = new Fl_Group(20, 170, 260, 45, "Powerball Numbers");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)6);
          o->labelsize(16);
          { pb_num1 = new Fl_Value_Input(35, 180, 35, 30);
            pb_num1->color((Fl_Color)58);
            pb_num1->textsize(16);
            pb_num1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num1
          { pb_num2 = new Fl_Value_Input(75, 180, 35, 30);
            pb_num2->color((Fl_Color)58);
            pb_num2->textsize(16);
            pb_num2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num2
          { pb_num3 = new Fl_Value_Input(115, 180, 35, 30);
            pb_num3->color((Fl_Color)58);
            pb_num3->textsize(16);
            pb_num3->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num3
          { pb_num4 = new Fl_Value_Input(155, 180, 35, 30);
            pb_num4->color((Fl_Color)58);
            pb_num4->textsize(16);
            pb_num4->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num4
          { pb_num5 = new Fl_Value_Input(195, 180, 35, 30);
            pb_num5->color((Fl_Color)58);
            pb_num5->textsize(16);
            pb_num5->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num5
          { pb_num6 = new Fl_Value_Input(235, 180, 35, 30);
            pb_num6->color((Fl_Color)58);
            pb_num6->textsize(16);
            pb_num6->textcolor((Fl_Color)3);
          } // Fl_Value_Input* pb_num6
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(375, 170, 85, 55, "Powerball");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)4);
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(16);
          { powerball_value = new Fl_Value_Input(395, 175, 50, 45);
            powerball_value->color((Fl_Color)59);
            powerball_value->selection_color((Fl_Color)58);
            powerball_value->labelsize(16);
            powerball_value->labelcolor((Fl_Color)6);
            powerball_value->textfont(1);
            powerball_value->textsize(18);
            powerball_value->textcolor((Fl_Color)6);
          } // Fl_Value_Input* powerball_value
          o->end();
        } // Fl_Group* o
        { Fl_Text_Display* o = powerball_number_view = new Fl_Text_Display(15, 250, 410, 355, "Powerball Numbers");
          powerball_number_view->box(FL_THIN_DOWN_BOX);
          powerball_number_view->color(FL_FOREGROUND_COLOR);
          powerball_number_view->selection_color(FL_FOREGROUND_COLOR);
          powerball_number_view->labeltype(FL_ENGRAVED_LABEL);
          powerball_number_view->labelsize(22);
          powerball_number_view->labelcolor((Fl_Color)80);
          powerball_number_view->textfont(13);
          powerball_number_view->textcolor((Fl_Color)2);
          Fl_Group::current()->resizable(powerball_number_view);
          o->buffer(powerballTextBuffer);
        } // Fl_Text_Display* powerball_number_view
        { ShowPowerballEntryWidget = new Fl_Button(440, 235, 120, 60, "Enter Powerball Numbers to play");
          ShowPowerballEntryWidget->color((Fl_Color)12);
          ShowPowerballEntryWidget->callback((Fl_Callback*)cb_ShowPowerballEntryWidget);
          ShowPowerballEntryWidget->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* ShowPowerballEntryWidget
        { ensurePowerball = new Fl_Check_Button(475, 150, 90, 55, "Ensure Powerball");
          ensurePowerball->down_box(FL_DOWN_BOX);
          ensurePowerball->callback((Fl_Callback*)cb_ensurePowerball);
          ensurePowerball->align(Fl_Align(132|FL_ALIGN_INSIDE));
        } // Fl_Check_Button* ensurePowerball
        powerball_tab->end();
      } // Fl_Group* powerball_tab
      { lottostrike_tab = new Fl_Group(0, 150, 565, 470, "Lotto Strike");
        lottostrike_tab->box(FL_DOWN_BOX);
        lottostrike_tab->color((Fl_Color)11);
        lottostrike_tab->selection_color((Fl_Color)29);
        lottostrike_tab->labeltype(FL_EMBOSSED_LABEL);
        lottostrike_tab->hide();
        { Fl_Group* o = new Fl_Group(20, 170, 280, 45, "Gold Lotto Numbers");
          o->box(FL_PLASTIC_DOWN_BOX);
          o->color((Fl_Color)6);
          o->labelsize(16);
          { lsnum1 = new Fl_Value_Input(45, 180, 35, 30);
            lsnum1->color((Fl_Color)58);
            lsnum1->textsize(16);
            lsnum1->textcolor((Fl_Color)3);
          } // Fl_Value_Input* lsnum1
          { lsnum2 = new Fl_Value_Input(85, 180, 35, 30);
            lsnum2->color((Fl_Color)58);
            lsnum2->textsize(16);
            lsnum2->textcolor((Fl_Color)3);
          } // Fl_Value_Input* lsnum2
          { lsnum3 = new Fl_Value_Input(125, 180, 35, 30);
            lsnum3->color((Fl_Color)58);
            lsnum3->textsize(16);
            lsnum3->textcolor((Fl_Color)3);
          } // Fl_Value_Input* lsnum3
          { lsnum4 = new Fl_Value_Input(165, 180, 35, 30);
            lsnum4->color((Fl_Color)58);
            lsnum4->textsize(16);
            lsnum4->textcolor((Fl_Color)3);
          } // Fl_Value_Input* lsnum4
          { lsnum5 = new Fl_Value_Input(205, 180, 35, 30);
            lsnum5->color((Fl_Color)58);
            lsnum5->textsize(16);
            lsnum5->textcolor((Fl_Color)3);
          } // Fl_Value_Input* lsnum5
          { lsnum6 = new Fl_Value_Input(245, 180, 35, 30);
            lsnum6->color((Fl_Color)58);
            lsnum6->textsize(16);
            lsnum6->textcolor((Fl_Color)3);
          } // Fl_Value_Input* lsnum6
          o->end();
        } // Fl_Group* o
        { Fl_Text_Display* o = lottostrike_number_view = new Fl_Text_Display(15, 250, 410, 355, "Lotto Strike Numbers");
          lottostrike_number_view->box(FL_THIN_DOWN_BOX);
          lottostrike_number_view->color(FL_FOREGROUND_COLOR);
          lottostrike_number_view->selection_color(FL_FOREGROUND_COLOR);
          lottostrike_number_view->labeltype(FL_ENGRAVED_LABEL);
          lottostrike_number_view->labelsize(22);
          lottostrike_number_view->labelcolor((Fl_Color)80);
          lottostrike_number_view->textfont(13);
          lottostrike_number_view->textcolor((Fl_Color)2);
          Fl_Group::current()->resizable(lottostrike_number_view);
          o->buffer(lottostrikeTextBuffer);
        } // Fl_Text_Display* lottostrike_number_view
        { ShowLottostrikeEntryWidget = new Fl_Button(440, 235, 120, 60, "Enter numbers with form");
          ShowLottostrikeEntryWidget->color((Fl_Color)3);
          ShowLottostrikeEntryWidget->callback((Fl_Callback*)cb_ShowLottostrikeEntryWidget);
          ShowLottostrikeEntryWidget->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* ShowLottostrikeEntryWidget
        lottostrike_tab->end();
        Fl_Group::current()->resizable(lottostrike_tab);
      } // Fl_Group* lottostrike_tab
      tabular->end();
    } // Fl_Tabs* tabular
    { Fl_Menu_Button* o = new Fl_Menu_Button(170, 55, 160, 25, "Winning Divisions");
      o->color((Fl_Color)14);
      o->menu(menu_Winning);
    } // Fl_Menu_Button* o
    { Fl_Button* o = new Fl_Button(460, 55, 80, 25, "License");
      o->color((Fl_Color)14);
      o->selection_color((Fl_Color)6);
      o->callback((Fl_Callback*)cb_License);
    } // Fl_Button* o
    { new Fl_Box(170, 55, 90, 25);
    } // Fl_Box* o
    lotto_gui->end();
  } // Fl_Window* lotto_gui
  { results_window = new Fl_Double_Window(415, 380, "Results");
    results_window->color((Fl_Color)14);
    results_window->user_data((void*)(this));
    results_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Button* o = new Fl_Button(315, 350, 85, 25, "Close");
      o->color((Fl_Color)22);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
      o->labelcolor((Fl_Color)1);
      o->callback((Fl_Callback*)cb_Close);
    } // Fl_Button* o
    { Fl_Box* o = new Fl_Box(0, 0, 415, 50, "RESULTS");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)137);
      o->labeltype(FL_SHADOW_LABEL);
      o->labelfont(14);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Text_Display* o = new Fl_Text_Display(5, 50, 410, 295);
      o->box(FL_DOWN_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->labelcolor((Fl_Color)2);
      o->textfont(13);
      o->textcolor((Fl_Color)2);
      o->buffer(textbuf_results);
    } // Fl_Text_Display* o
    { Fl_Button* o = new Fl_Button(15, 350, 85, 25, "Save");
      o->color((Fl_Color)22);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
      o->labelcolor((Fl_Color)1);
      o->callback((Fl_Callback*)cb_Save1);
    } // Fl_Button* o
    results_window->set_modal();
    results_window->end();
  } // Fl_Double_Window* results_window
  { divisions_window = new Fl_Double_Window(505, 295, "Tattslotto Divisions");
    divisions_window->color((Fl_Color)14);
    divisions_window->user_data((void*)(this));
    divisions_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Text_Display* o = new Fl_Text_Display(15, 70, 15, 20, "Division 1 : 6 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 100, 15, 20, "Division 2 : 5 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 130, 15, 20, "Division 3 : 5 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 160, 15, 20, "Division 4 : 4 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 190, 15, 20, "Division 5 : 3 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 220, 15, 20, "Division 6 : 1 number and 2 supplementaries");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Box* o = new Fl_Box(25, 10, 470, 40, "Tattslotto Winning Divisions");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(400, 255, 95, 30, "Close");
      o->callback((Fl_Callback*)cb_Close1);
    } // Fl_Button* o
    divisions_window->set_modal();
    divisions_window->end();
  } // Fl_Double_Window* divisions_window
  { help_window = new Fl_Double_Window(555, 440, "HELP / MANUAL");
    help_window->color((Fl_Color)14);
    help_window->user_data((void*)(this));
    help_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Box* o = new Fl_Box(15, 5, 535, 40, "HELP / MANUAL");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labeltype(FL_SHADOW_LABEL);
      o->labelfont(14);
      o->labelsize(26);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(230, 405, 85, 25, "Close");
      o->color((Fl_Color)22);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
      o->labelcolor((Fl_Color)1);
      o->callback((Fl_Callback*)cb_Close2);
    } // Fl_Button* o
    { helpView = new Fl_Help_View(15, 45, 535, 355);
      helpView->labelcolor((Fl_Color)18);
      loadHelp();
    } // Fl_Help_View* helpView
    help_window->end();
  } // Fl_Double_Window* help_window
  { oz_divisions_window = new Fl_Double_Window(495, 355, "OzLotto Divisions");
    oz_divisions_window->color((Fl_Color)14);
    oz_divisions_window->user_data((void*)(this));
    oz_divisions_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Text_Display* o = new Fl_Text_Display(15, 70, 15, 20, "Division 1 : 7 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 100, 15, 20, "Division 2 : 6 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 130, 15, 20, "Division 3 : 6 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 160, 15, 20, "Division 4 : 5 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 190, 15, 20, "Division 5 : 5 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 220, 15, 20, "Division 6 : 4 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 250, 15, 20, "Division 7 : 3 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Box* o = new Fl_Box(25, 10, 450, 40, "Ozlotto Winning Divisions");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(385, 295, 95, 30, "Close");
      o->callback((Fl_Callback*)cb_Close3);
    } // Fl_Button* o
    oz_divisions_window->set_modal();
    oz_divisions_window->end();
  } // Fl_Double_Window* oz_divisions_window
  { powerball_divisions_window = new Fl_Double_Window(555, 330, "Divisions");
    powerball_divisions_window->color((Fl_Color)14);
    powerball_divisions_window->user_data((void*)(this));
    powerball_divisions_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Text_Display* o = new Fl_Text_Display(15, 70, 15, 20, "Division 1 : 6 numbers and the powerball");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 100, 15, 20, "Division 2 : 6 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 130, 15, 20, "Division 3 : 6 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 160, 15, 20, "Division 4 : 5 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 190, 15, 20, "Division 5 : 5 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 215, 15, 20, "Division 6 : 4 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 245, 15, 20, "Division 7 : 3 numbers and a supplementary");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Box* o = new Fl_Box(25, 10, 560, 40, "Powerball Winning Divisions");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(395, 280, 95, 30, "Close");
      o->callback((Fl_Callback*)cb_Close4);
    } // Fl_Button* o
    powerball_divisions_window->set_modal();
    powerball_divisions_window->end();
  } // Fl_Double_Window* powerball_divisions_window
  { TattsNumberEntryWindow = new Fl_Double_Window(430, 565, "Tattslotto Number");
    TattsNumberEntryWindow->color((Fl_Color)14);
    TattsNumberEntryWindow->user_data((void*)(this));
    { TattsEntryGroup = new Fl_Group(10, 20, 405, 530, "Enter Tattslotto Numbers");
      { Fl_Button* o = new Fl_Button(20, 530, 105, 20, "OK");
        o->color((Fl_Color)14);
        o->callback((Fl_Callback*)cb_OK);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(300, 530, 105, 20, "Cancel");
        o->color((Fl_Color)14);
        o->callback((Fl_Callback*)cb_Cancel);
      } // Fl_Button* o
      TattsEntryGroup->end();
    } // Fl_Group* TattsEntryGroup
    TattsNumberEntryWindow->end();
  } // Fl_Double_Window* TattsNumberEntryWindow
  { OzlottoNumberEntryWindow = new Fl_Double_Window(430, 565, "Ozlotto Number");
    OzlottoNumberEntryWindow->color((Fl_Color)14);
    OzlottoNumberEntryWindow->user_data((void*)(this));
    { OzlottoEntryGroup = new Fl_Group(10, 20, 405, 530, "Enter Ozlotto Numbers");
      { Fl_Button* o = new Fl_Button(20, 530, 105, 20, "OK");
        o->color((Fl_Color)14);
        o->callback((Fl_Callback*)cb_OK1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(300, 530, 105, 20, "Cancel");
        o->color((Fl_Color)14);
        o->callback((Fl_Callback*)cb_Cancel1);
      } // Fl_Button* o
      OzlottoEntryGroup->end();
    } // Fl_Group* OzlottoEntryGroup
    OzlottoNumberEntryWindow->end();
  } // Fl_Double_Window* OzlottoNumberEntryWindow
  { LottostrikeNumberEntryWindow = new Fl_Double_Window(430, 565, "Lotto Strike Number");
    LottostrikeNumberEntryWindow->color((Fl_Color)14);
    LottostrikeNumberEntryWindow->user_data((void*)(this));
    { LottostrikeEntryGroup = new Fl_Group(10, 20, 405, 530, "Enter Lotto Strike Numbers");
      { Fl_Button* o = new Fl_Button(20, 530, 105, 20, "OK");
        o->color((Fl_Color)14);
        o->callback((Fl_Callback*)cb_OK2);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(300, 530, 105, 20, "Cancel");
        o->color((Fl_Color)14);
        o->callback((Fl_Callback*)cb_Cancel2);
      } // Fl_Button* o
      LottostrikeEntryGroup->end();
    } // Fl_Group* LottostrikeEntryGroup
    LottostrikeNumberEntryWindow->end();
  } // Fl_Double_Window* LottostrikeNumberEntryWindow
  { Numberentry = new Fl_Double_Window(350, 250, "Number Entry");
    Numberentry->user_data((void*)(this));
    Numberentry->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { button_1 = new Fl_Light_Button(15, 25, 40, 25, "1");
      button_1->callback((Fl_Callback*)cb_button_1);
    } // Fl_Light_Button* button_1
    { button_2 = new Fl_Light_Button(55, 25, 40, 25, "2");
      button_2->callback((Fl_Callback*)cb_button_2);
    } // Fl_Light_Button* button_2
    { button_3 = new Fl_Light_Button(95, 25, 40, 25, "3");
      button_3->callback((Fl_Callback*)cb_button_3);
    } // Fl_Light_Button* button_3
    { button_4 = new Fl_Light_Button(135, 25, 40, 25, "4");
      button_4->callback((Fl_Callback*)cb_button_4);
    } // Fl_Light_Button* button_4
    { button_5 = new Fl_Light_Button(175, 25, 40, 25, "5");
      button_5->callback((Fl_Callback*)cb_button_5);
    } // Fl_Light_Button* button_5
    { button_6 = new Fl_Light_Button(215, 25, 40, 25, "6");
      button_6->callback((Fl_Callback*)cb_button_6);
    } // Fl_Light_Button* button_6
    { button_7 = new Fl_Light_Button(255, 25, 40, 25, "7");
      button_7->callback((Fl_Callback*)cb_button_7);
    } // Fl_Light_Button* button_7
    { button_8 = new Fl_Light_Button(295, 25, 40, 25, "8");
      button_8->callback((Fl_Callback*)cb_button_8);
    } // Fl_Light_Button* button_8
    { button_9 = new Fl_Light_Button(15, 50, 40, 25, "9");
      button_9->callback((Fl_Callback*)cb_button_9);
    } // Fl_Light_Button* button_9
    { button_10 = new Fl_Light_Button(55, 50, 40, 25, "10");
      button_10->callback((Fl_Callback*)cb_button_10);
    } // Fl_Light_Button* button_10
    { button_11 = new Fl_Light_Button(95, 50, 40, 25, "11");
      button_11->callback((Fl_Callback*)cb_button_11);
    } // Fl_Light_Button* button_11
    { button_12 = new Fl_Light_Button(135, 50, 40, 25, "12");
      button_12->callback((Fl_Callback*)cb_button_12);
    } // Fl_Light_Button* button_12
    { button_13 = new Fl_Light_Button(175, 50, 40, 25, "13");
      button_13->callback((Fl_Callback*)cb_button_13);
    } // Fl_Light_Button* button_13
    { button_14 = new Fl_Light_Button(215, 50, 40, 25, "14");
      button_14->callback((Fl_Callback*)cb_button_14);
    } // Fl_Light_Button* button_14
    { button_15 = new Fl_Light_Button(255, 50, 40, 25, "15");
      button_15->callback((Fl_Callback*)cb_button_15);
    } // Fl_Light_Button* button_15
    { button_16 = new Fl_Light_Button(295, 50, 40, 25, "16");
      button_16->callback((Fl_Callback*)cb_button_16);
    } // Fl_Light_Button* button_16
    { button_17 = new Fl_Light_Button(15, 75, 40, 25, "17");
      button_17->callback((Fl_Callback*)cb_button_17);
    } // Fl_Light_Button* button_17
    { button_18 = new Fl_Light_Button(55, 75, 40, 25, "18");
      button_18->callback((Fl_Callback*)cb_button_18);
    } // Fl_Light_Button* button_18
    { button_19 = new Fl_Light_Button(95, 75, 40, 25, "19");
      button_19->callback((Fl_Callback*)cb_button_19);
    } // Fl_Light_Button* button_19
    { button_20 = new Fl_Light_Button(135, 75, 40, 25, "20");
      button_20->callback((Fl_Callback*)cb_button_20);
    } // Fl_Light_Button* button_20
    { button_21 = new Fl_Light_Button(175, 75, 40, 25, "21");
      button_21->callback((Fl_Callback*)cb_button_21);
    } // Fl_Light_Button* button_21
    { button_22 = new Fl_Light_Button(215, 75, 40, 25, "22");
      button_22->callback((Fl_Callback*)cb_button_22);
    } // Fl_Light_Button* button_22
    { button_23 = new Fl_Light_Button(255, 75, 40, 25, "23");
      button_23->callback((Fl_Callback*)cb_button_23);
    } // Fl_Light_Button* button_23
    { button_24 = new Fl_Light_Button(295, 75, 40, 25, "24");
      button_24->callback((Fl_Callback*)cb_button_24);
    } // Fl_Light_Button* button_24
    { button_25 = new Fl_Light_Button(15, 100, 40, 25, "25");
      button_25->callback((Fl_Callback*)cb_button_25);
    } // Fl_Light_Button* button_25
    { button_26 = new Fl_Light_Button(55, 100, 40, 25, "26");
      button_26->callback((Fl_Callback*)cb_button_26);
    } // Fl_Light_Button* button_26
    { button_27 = new Fl_Light_Button(95, 100, 40, 25, "27");
      button_27->callback((Fl_Callback*)cb_button_27);
    } // Fl_Light_Button* button_27
    { button_28 = new Fl_Light_Button(135, 100, 40, 25, "28");
      button_28->callback((Fl_Callback*)cb_button_28);
    } // Fl_Light_Button* button_28
    { button_29 = new Fl_Light_Button(175, 100, 40, 25, "29");
      button_29->callback((Fl_Callback*)cb_button_29);
    } // Fl_Light_Button* button_29
    { button_30 = new Fl_Light_Button(215, 100, 40, 25, "30");
      button_30->callback((Fl_Callback*)cb_button_30);
    } // Fl_Light_Button* button_30
    { button_31 = new Fl_Light_Button(255, 100, 40, 25, "31");
      button_31->callback((Fl_Callback*)cb_button_31);
    } // Fl_Light_Button* button_31
    { button_32 = new Fl_Light_Button(295, 100, 40, 25, "32");
      button_32->callback((Fl_Callback*)cb_button_32);
    } // Fl_Light_Button* button_32
    { button_33 = new Fl_Light_Button(15, 125, 40, 25, "33");
      button_33->callback((Fl_Callback*)cb_button_33);
    } // Fl_Light_Button* button_33
    { button_34 = new Fl_Light_Button(55, 125, 40, 25, "34");
      button_34->callback((Fl_Callback*)cb_button_34);
    } // Fl_Light_Button* button_34
    { button_35 = new Fl_Light_Button(95, 125, 40, 25, "35");
      button_35->callback((Fl_Callback*)cb_button_35);
    } // Fl_Light_Button* button_35
    { button_36 = new Fl_Light_Button(135, 125, 40, 25, "36");
      button_36->callback((Fl_Callback*)cb_button_36);
    } // Fl_Light_Button* button_36
    { button_37 = new Fl_Light_Button(175, 125, 40, 25, "37");
      button_37->callback((Fl_Callback*)cb_button_37);
    } // Fl_Light_Button* button_37
    { button_38 = new Fl_Light_Button(215, 125, 40, 25, "38");
      button_38->callback((Fl_Callback*)cb_button_38);
    } // Fl_Light_Button* button_38
    { button_39 = new Fl_Light_Button(255, 125, 40, 25, "39");
      button_39->callback((Fl_Callback*)cb_button_39);
    } // Fl_Light_Button* button_39
    { button_40 = new Fl_Light_Button(295, 125, 40, 25, "40");
      button_40->callback((Fl_Callback*)cb_button_40);
    } // Fl_Light_Button* button_40
    { button_41 = new Fl_Light_Button(15, 150, 40, 25, "41");
      button_41->callback((Fl_Callback*)cb_button_41);
    } // Fl_Light_Button* button_41
    { button_42 = new Fl_Light_Button(55, 150, 40, 25, "42");
      button_42->callback((Fl_Callback*)cb_button_42);
    } // Fl_Light_Button* button_42
    { button_43 = new Fl_Light_Button(95, 150, 40, 25, "43");
      button_43->callback((Fl_Callback*)cb_button_43);
    } // Fl_Light_Button* button_43
    { button_44 = new Fl_Light_Button(135, 150, 40, 25, "44");
      button_44->callback((Fl_Callback*)cb_button_44);
    } // Fl_Light_Button* button_44
    { button_45 = new Fl_Light_Button(175, 150, 40, 25, "45");
      button_45->callback((Fl_Callback*)cb_button_45);
    } // Fl_Light_Button* button_45
    { Fl_Button* o = new Fl_Button(40, 210, 60, 30, "OK");
      o->labeltype(FL_EMBOSSED_LABEL);
      o->callback((Fl_Callback*)cb_OK3);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(255, 210, 60, 30, "Cancel");
      o->labeltype(FL_EMBOSSED_LABEL);
      o->callback((Fl_Callback*)cb_Cancel3);
    } // Fl_Button* o
    Numberentry->end();
  } // Fl_Double_Window* Numberentry
  { PowerballNumberEntryWindow = new Fl_Double_Window(430, 565, "Powerball Number");
    PowerballNumberEntryWindow->color((Fl_Color)14);
    PowerballNumberEntryWindow->user_data((void*)(this));
    PowerballNumberEntryWindow->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { PowerballEntryGroup = new Fl_Group(10, 20, 405, 530, "Enter Powerball Numbers");
      { Fl_Button* o = new Fl_Button(20, 530, 105, 20, "OK");
        o->color((Fl_Color)14);
        o->callback((Fl_Callback*)cb_OK4);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(300, 530, 105, 20, "Cancel");
        o->color((Fl_Color)14);
        o->callback((Fl_Callback*)cb_Cancel4);
      } // Fl_Button* o
      PowerballEntryGroup->end();
    } // Fl_Group* PowerballEntryGroup
    PowerballNumberEntryWindow->end();
  } // Fl_Double_Window* PowerballNumberEntryWindow
  { lottostrike_divisions_window = new Fl_Double_Window(490, 240, "Lotto Strike Divisions");
    lottostrike_divisions_window->color((Fl_Color)14);
    lottostrike_divisions_window->user_data((void*)(this));
    lottostrike_divisions_window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Text_Display* o = new Fl_Text_Display(15, 70, 15, 20, "Division 1 : All 4 of the 1st four numbers in order");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 100, 15, 20, "Division 2 : 3 of the first four numbers in order");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 130, 15, 20, "Division 3 : 2 of the first 4 numbers in order");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(15, 160, 15, 20, "Division 4 : 1 of the first 4 numbers");
      o->box(FL_NO_BOX);
      o->labelsize(18);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Box* o = new Fl_Box(25, 10, 445, 40, "Lotto Strike Winning Divisions");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->labelsize(28);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(360, 190, 95, 35, "Close");
      o->callback((Fl_Callback*)cb_Close5);
    } // Fl_Button* o
    lottostrike_divisions_window->set_modal();
    lottostrike_divisions_window->end();
  } // Fl_Double_Window* lottostrike_divisions_window
  { LicenseWindow = new Fl_Double_Window(590, 570, "License");
    LicenseWindow->color((Fl_Color)14);
    LicenseWindow->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(0, 0, 590, 55, "License");
      o->box(FL_ENGRAVED_BOX);
      o->color(FL_SELECTION_COLOR);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(36);
      o->labelcolor((Fl_Color)6);
    } // Fl_Box* o
    { Fl_Text_Display* o = new Fl_Text_Display(0, 55, 585, 465);
      o->box(FL_DOWN_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->labelfont(13);
      o->labelsize(10);
      o->textfont(13);
      o->textsize(12);
      o->textcolor((Fl_Color)6);
      o->align(Fl_Align(129));
      o->buffer(licenseTextBuffer);
    } // Fl_Text_Display* o
    { Fl_Button* o = new Fl_Button(250, 540, 145, 25, "Close");
      o->color((Fl_Color)31);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->callback((Fl_Callback*)cb_Close6);
    } // Fl_Button* o
    { Fl_Box* o = new Fl_Box(0, 520, 265, 20, "(C) Dennis Katsonis   2014");
      o->labelfont(14);
    } // Fl_Box* o
    LicenseWindow->end();
  } // Fl_Double_Window* LicenseWindow
  return LicenseWindow;
}

int UserInterface::quit() {
  this->lotto_gui->hide();
  this->divisions_window->hide();
  this->results_window->hide();
  this->TattsNumberEntryWindow->hide();;
  return 0;
  // Closes the program by hiding the main gui.  Hiding the main window ends the 
  // execution loop.
}

void UserInterface::close_results_window() {
  this->results_window->hide();
}

void UserInterface::close_tatts_divisions_window() {
  this->divisions_window->hide();
}

void UserInterface::show_tatts_divisions_window() {
  this->divisions_window->show();
}

void UserInterface::show_help_window() {
  this->help_window->show();
}

void UserInterface::close_help_window() {
  this->help_window->hide();
}

void UserInterface::show_oz_divisions_window() {
  this->oz_divisions_window->show();
}

void UserInterface::show_powerball_divisions_window() {
  this->powerball_divisions_window->show();
}

void UserInterface::close_oz_divisions_window() {
  this->oz_divisions_window->hide();
}

void UserInterface::close_powerball_divisions_window() {
  this->powerball_divisions_window->hide();
}

void UserInterface::clear_results() {
}

void UserInterface::show_tatts_entry_window() {
  this->TattsNumberEntryWindow->show();
}

void UserInterface::hide_tatts_entry_window() {
  this->TattsNumberEntryWindow->hide();
}

void UserInterface::show_ozlotto_entry_window() {
  this->OzlottoNumberEntryWindow->show();
}

void UserInterface::hide_ozlotto_entry_window() {
  this->OzlottoNumberEntryWindow->hide();
}

void UserInterface::show_powerball_entry_window() {
  this->PowerballNumberEntryWindow->show();
}

void UserInterface::hide_powerball_entry_window() {
  this->PowerballNumberEntryWindow->hide();
}

void UserInterface::saveResults() {
  return;
}

void UserInterface::show_Numberentry_window() {
  this->Numberentry->show();
}

void UserInterface::hide_Numberentry_window() {
  this->Numberentry->hide();
}

void UserInterface::show_lottostrike_entry_window() {
  this->LottostrikeNumberEntryWindow->show();
}

void UserInterface::hide_lottostrike_entry_window() {
  this->LottostrikeNumberEntryWindow->hide();
}

void UserInterface::show_lottostrike_divisions_window() {
  this->lottostrike_divisions_window->show();
}

void UserInterface::close_lottostrike_divisions_window() {
  this->lottostrike_divisions_window->hide();
}

void UserInterface::show_license_window() {
  this->LicenseWindow->show();
}

void UserInterface::close_license_window() {
  this->LicenseWindow->hide();
}
