// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef AussieLottoGUI_h
#define AussieLottoGUI_h
#include <FL/Fl.H>
#include "types.h"
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Help_View.H>
#include <FL/Fl_Light_Button.H>

class UserInterface {
public:
  Fl_Text_Buffer *ozlottoTextBuffer; 
  Fl_Text_Buffer *lottostrikeTextBuffer; 
  Fl_Text_Buffer *licenseTextBuffer; 
  Fl_Text_Buffer *powerballTextBuffer; 
  Fl_Text_Buffer *tattslottoTextBuffer; 
  Fl_Text_Buffer *textbuf_results; 
  Fl_Text_Buffer *help_text; 
  Fl_Window* make_window();
  Fl_Window *lotto_gui;
private:
  inline void cb_Quit_i(Fl_Button*, void*);
  static void cb_Quit(Fl_Button*, void*);
  static Fl_Menu_Item menu_File[];
  inline void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  inline void cb_Save_i(Fl_Menu_*, void*);
  static void cb_Save(Fl_Menu_*, void*);
  inline void cb_Exit_i(Fl_Menu_*, void*);
  static void cb_Exit(Fl_Menu_*, void*);
  inline void cb_About_i(Fl_Button*, void*);
  static void cb_About(Fl_Button*, void*);
  inline void cb_Generate_i(Fl_Button*, void*);
  static void cb_Generate(Fl_Button*, void*);
  inline void cb_Check_i(Fl_Button*, void*);
  static void cb_Check(Fl_Button*, void*);
public:
  Fl_Value_Input *num_games;
  static Fl_Menu_Item menu_Options[];
private:
  inline void cb_Check1_i(Fl_Menu_*, void*);
  static void cb_Check1(Fl_Menu_*, void*);
  inline void cb_Generate1_i(Fl_Menu_*, void*);
  static void cb_Generate1(Fl_Menu_*, void*);
  inline void cb_Clear_i(Fl_Menu_*, void*);
  static void cb_Clear(Fl_Menu_*, void*);
  inline void cb_Clear1_i(Fl_Menu_*, void*);
  static void cb_Clear1(Fl_Menu_*, void*);
  inline void cb_Help_i(Fl_Button*, void*);
  static void cb_Help(Fl_Button*, void*);
public:
  Fl_Tabs *tabular;
private:
  inline void cb_tabular_i(Fl_Tabs*, void*);
  static void cb_tabular(Fl_Tabs*, void*);
public:
  Fl_Group *tattslotto_tab;
  Fl_Value_Input *num1;
  Fl_Value_Input *num2;
  Fl_Value_Input *num3;
  Fl_Value_Input *num4;
  Fl_Value_Input *num5;
  Fl_Value_Input *num6;
  Fl_Value_Input *supp1;
  Fl_Value_Input *supp2;
  Fl_Text_Display *number_view;
  Fl_Button *ShowTattsEntryWidget;
private:
  inline void cb_ShowTattsEntryWidget_i(Fl_Button*, void*);
  static void cb_ShowTattsEntryWidget(Fl_Button*, void*);
  inline void cb_Enter_i(Fl_Button*, void*);
  static void cb_Enter(Fl_Button*, void*);
public:
  Fl_Group *ozlotto_tab;
  Fl_Value_Input *oz_num1;
  Fl_Value_Input *oz_num2;
  Fl_Value_Input *oz_num3;
  Fl_Value_Input *oz_num4;
  Fl_Value_Input *oz_num5;
  Fl_Value_Input *oz_num6;
  Fl_Value_Input *oz_num7;
  Fl_Value_Input *oz_supp1;
  Fl_Value_Input *oz_supp2;
  Fl_Text_Display *oz_number_view;
  Fl_Button *ShowOzlottoEntryWidget;
private:
  inline void cb_ShowOzlottoEntryWidget_i(Fl_Button*, void*);
  static void cb_ShowOzlottoEntryWidget(Fl_Button*, void*);
  inline void cb_Enter1_i(Fl_Button*, void*);
  static void cb_Enter1(Fl_Button*, void*);
public:
  Fl_Group *powerball_tab;
  Fl_Value_Input *pb_num1;
  Fl_Value_Input *pb_num2;
  Fl_Value_Input *pb_num3;
  Fl_Value_Input *pb_num4;
  Fl_Value_Input *pb_num5;
  Fl_Value_Input *pb_num6;
  Fl_Value_Input *powerball_value;
  Fl_Text_Display *powerball_number_view;
  Fl_Button *ShowPowerballEntryWidget;
private:
  inline void cb_ShowPowerballEntryWidget_i(Fl_Button*, void*);
  static void cb_ShowPowerballEntryWidget(Fl_Button*, void*);
public:
  Fl_Check_Button *ensurePowerball;
private:
  inline void cb_ensurePowerball_i(Fl_Check_Button*, void*);
  static void cb_ensurePowerball(Fl_Check_Button*, void*);
public:
  Fl_Group *lottostrike_tab;
  Fl_Value_Input *lsnum1;
  Fl_Value_Input *lsnum2;
  Fl_Value_Input *lsnum3;
  Fl_Value_Input *lsnum4;
  Fl_Value_Input *lsnum5;
  Fl_Value_Input *lsnum6;
  Fl_Text_Display *lottostrike_number_view;
  Fl_Button *ShowLottostrikeEntryWidget;
private:
  inline void cb_ShowLottostrikeEntryWidget_i(Fl_Button*, void*);
  static void cb_ShowLottostrikeEntryWidget(Fl_Button*, void*);
  static Fl_Menu_Item menu_Winning[];
  inline void cb_Tattslotto_i(Fl_Menu_*, void*);
  static void cb_Tattslotto(Fl_Menu_*, void*);
  inline void cb_Oz_i(Fl_Menu_*, void*);
  static void cb_Oz(Fl_Menu_*, void*);
  inline void cb_Powerball_i(Fl_Menu_*, void*);
  static void cb_Powerball(Fl_Menu_*, void*);
  inline void cb_Lotto_i(Fl_Menu_*, void*);
  static void cb_Lotto(Fl_Menu_*, void*);
  inline void cb_License_i(Fl_Button*, void*);
  static void cb_License(Fl_Button*, void*);
public:
  Fl_Double_Window *results_window;
private:
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
  inline void cb_Save1_i(Fl_Button*, void*);
  static void cb_Save1(Fl_Button*, void*);
public:
  Fl_Double_Window *divisions_window;
private:
  inline void cb_Close1_i(Fl_Button*, void*);
  static void cb_Close1(Fl_Button*, void*);
public:
  Fl_Double_Window *help_window;
private:
  inline void cb_Close2_i(Fl_Button*, void*);
  static void cb_Close2(Fl_Button*, void*);
public:
  Fl_Help_View *helpView;
  Fl_Double_Window *oz_divisions_window;
private:
  inline void cb_Close3_i(Fl_Button*, void*);
  static void cb_Close3(Fl_Button*, void*);
public:
  Fl_Double_Window *powerball_divisions_window;
private:
  inline void cb_Close4_i(Fl_Button*, void*);
  static void cb_Close4(Fl_Button*, void*);
public:
  Fl_Double_Window *TattsNumberEntryWindow;
  Fl_Group *TattsEntryGroup;
private:
  inline void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
public:
  Fl_Double_Window *OzlottoNumberEntryWindow;
  Fl_Group *OzlottoEntryGroup;
private:
  inline void cb_OK1_i(Fl_Button*, void*);
  static void cb_OK1(Fl_Button*, void*);
  inline void cb_Cancel1_i(Fl_Button*, void*);
  static void cb_Cancel1(Fl_Button*, void*);
public:
  Fl_Double_Window *LottostrikeNumberEntryWindow;
  Fl_Group *LottostrikeEntryGroup;
private:
  inline void cb_OK2_i(Fl_Button*, void*);
  static void cb_OK2(Fl_Button*, void*);
  inline void cb_Cancel2_i(Fl_Button*, void*);
  static void cb_Cancel2(Fl_Button*, void*);
public:
  Fl_Double_Window *Numberentry;
  Fl_Light_Button *button_1;
private:
  inline void cb_button_1_i(Fl_Light_Button*, void*);
  static void cb_button_1(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_2;
private:
  inline void cb_button_2_i(Fl_Light_Button*, void*);
  static void cb_button_2(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_3;
private:
  inline void cb_button_3_i(Fl_Light_Button*, void*);
  static void cb_button_3(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_4;
private:
  inline void cb_button_4_i(Fl_Light_Button*, void*);
  static void cb_button_4(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_5;
private:
  inline void cb_button_5_i(Fl_Light_Button*, void*);
  static void cb_button_5(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_6;
private:
  inline void cb_button_6_i(Fl_Light_Button*, void*);
  static void cb_button_6(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_7;
private:
  inline void cb_button_7_i(Fl_Light_Button*, void*);
  static void cb_button_7(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_8;
private:
  inline void cb_button_8_i(Fl_Light_Button*, void*);
  static void cb_button_8(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_9;
private:
  inline void cb_button_9_i(Fl_Light_Button*, void*);
  static void cb_button_9(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_10;
private:
  inline void cb_button_10_i(Fl_Light_Button*, void*);
  static void cb_button_10(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_11;
private:
  inline void cb_button_11_i(Fl_Light_Button*, void*);
  static void cb_button_11(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_12;
private:
  inline void cb_button_12_i(Fl_Light_Button*, void*);
  static void cb_button_12(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_13;
private:
  inline void cb_button_13_i(Fl_Light_Button*, void*);
  static void cb_button_13(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_14;
private:
  inline void cb_button_14_i(Fl_Light_Button*, void*);
  static void cb_button_14(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_15;
private:
  inline void cb_button_15_i(Fl_Light_Button*, void*);
  static void cb_button_15(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_16;
private:
  inline void cb_button_16_i(Fl_Light_Button*, void*);
  static void cb_button_16(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_17;
private:
  inline void cb_button_17_i(Fl_Light_Button*, void*);
  static void cb_button_17(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_18;
private:
  inline void cb_button_18_i(Fl_Light_Button*, void*);
  static void cb_button_18(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_19;
private:
  inline void cb_button_19_i(Fl_Light_Button*, void*);
  static void cb_button_19(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_20;
private:
  inline void cb_button_20_i(Fl_Light_Button*, void*);
  static void cb_button_20(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_21;
private:
  inline void cb_button_21_i(Fl_Light_Button*, void*);
  static void cb_button_21(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_22;
private:
  inline void cb_button_22_i(Fl_Light_Button*, void*);
  static void cb_button_22(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_23;
private:
  inline void cb_button_23_i(Fl_Light_Button*, void*);
  static void cb_button_23(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_24;
private:
  inline void cb_button_24_i(Fl_Light_Button*, void*);
  static void cb_button_24(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_25;
private:
  inline void cb_button_25_i(Fl_Light_Button*, void*);
  static void cb_button_25(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_26;
private:
  inline void cb_button_26_i(Fl_Light_Button*, void*);
  static void cb_button_26(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_27;
private:
  inline void cb_button_27_i(Fl_Light_Button*, void*);
  static void cb_button_27(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_28;
private:
  inline void cb_button_28_i(Fl_Light_Button*, void*);
  static void cb_button_28(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_29;
private:
  inline void cb_button_29_i(Fl_Light_Button*, void*);
  static void cb_button_29(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_30;
private:
  inline void cb_button_30_i(Fl_Light_Button*, void*);
  static void cb_button_30(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_31;
private:
  inline void cb_button_31_i(Fl_Light_Button*, void*);
  static void cb_button_31(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_32;
private:
  inline void cb_button_32_i(Fl_Light_Button*, void*);
  static void cb_button_32(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_33;
private:
  inline void cb_button_33_i(Fl_Light_Button*, void*);
  static void cb_button_33(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_34;
private:
  inline void cb_button_34_i(Fl_Light_Button*, void*);
  static void cb_button_34(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_35;
private:
  inline void cb_button_35_i(Fl_Light_Button*, void*);
  static void cb_button_35(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_36;
private:
  inline void cb_button_36_i(Fl_Light_Button*, void*);
  static void cb_button_36(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_37;
private:
  inline void cb_button_37_i(Fl_Light_Button*, void*);
  static void cb_button_37(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_38;
private:
  inline void cb_button_38_i(Fl_Light_Button*, void*);
  static void cb_button_38(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_39;
private:
  inline void cb_button_39_i(Fl_Light_Button*, void*);
  static void cb_button_39(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_40;
private:
  inline void cb_button_40_i(Fl_Light_Button*, void*);
  static void cb_button_40(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_41;
private:
  inline void cb_button_41_i(Fl_Light_Button*, void*);
  static void cb_button_41(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_42;
private:
  inline void cb_button_42_i(Fl_Light_Button*, void*);
  static void cb_button_42(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_43;
private:
  inline void cb_button_43_i(Fl_Light_Button*, void*);
  static void cb_button_43(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_44;
private:
  inline void cb_button_44_i(Fl_Light_Button*, void*);
  static void cb_button_44(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *button_45;
private:
  inline void cb_button_45_i(Fl_Light_Button*, void*);
  static void cb_button_45(Fl_Light_Button*, void*);
  inline void cb_OK3_i(Fl_Button*, void*);
  static void cb_OK3(Fl_Button*, void*);
  inline void cb_Cancel3_i(Fl_Button*, void*);
  static void cb_Cancel3(Fl_Button*, void*);
public:
  Fl_Double_Window *PowerballNumberEntryWindow;
  Fl_Group *PowerballEntryGroup;
private:
  inline void cb_OK4_i(Fl_Button*, void*);
  static void cb_OK4(Fl_Button*, void*);
  inline void cb_Cancel4_i(Fl_Button*, void*);
  static void cb_Cancel4(Fl_Button*, void*);
public:
  Fl_Double_Window *lottostrike_divisions_window;
private:
  inline void cb_Close5_i(Fl_Button*, void*);
  static void cb_Close5(Fl_Button*, void*);
public:
  Fl_Double_Window *LicenseWindow;
private:
  inline void cb_Close6_i(Fl_Button*, void*);
  static void cb_Close6(Fl_Button*, void*);
public:
  int quit();
  void close_results_window();
  void close_tatts_divisions_window();
  void show_tatts_divisions_window();
  void show_help_window();
  void close_help_window();
  void show_oz_divisions_window();
  void show_powerball_divisions_window();
  void close_oz_divisions_window();
  void close_powerball_divisions_window();
  virtual int open_file();
  virtual int save_file();
  virtual void clear_results();
  virtual void check_lotto();
  virtual int generate();
  virtual void clear_lotto();
  virtual void changeTab();
  virtual void show_tatts_entry_window();
  void hide_tatts_entry_window();
  virtual void show_ozlotto_entry_window();
  void hide_ozlotto_entry_window();
  virtual void tattsEntry();
  virtual void ozlottoEntry();
  virtual void powerballEntry();
  virtual void show_powerball_entry_window();
  void hide_powerball_entry_window();
  virtual void saveResults();
  virtual void NumberSelectorUpdate(int x);
  virtual void show_Numberentry_window();
  virtual void hide_Numberentry_window();
  virtual void submitButtonNums();
  virtual void clearNumberSelector();
  virtual void loadHelp();
  virtual void show_lottostrike_entry_window();
  void hide_lottostrike_entry_window();
  virtual void lottostrikeEntry();
  void show_lottostrike_divisions_window();
  void close_lottostrike_divisions_window();
  virtual void show_license_window();
  void close_license_window();
  virtual void ensurePowerballButton();
};
#endif
