// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "DrawHistoryManagerGUI.h"

void DrawHistoryManagerGUI::cb_Download_i(Fl_Button*, void*) {
  update_window->show();
}
void DrawHistoryManagerGUI::cb_Download(Fl_Button* o, void* v) {
  ((DrawHistoryManagerGUI*)(o->parent()->user_data()))->cb_Download_i(o,v);
}

Fl_Double_Window* DrawHistoryManagerGUI::make_window() {
  { main_window = new Fl_Double_Window(700, 455, "Results Manager");
    main_window->color((Fl_Color)12);
    main_window->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(0, 0, 700, 25, "Result Manager");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->selection_color(FL_FOREGROUND_COLOR);
      o->labelsize(18);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { new Fl_Button(625, 25, 75, 25, "Close");
    } // Fl_Button* o
    { Fl_Box* o = new Fl_Box(5, 150, 210, 30, "Tattslotto");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 180, 210, 30, "Oz Lotto");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 210, 210, 30, "Powerball");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 240, 210, 30, "Set For Life");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 120, 210, 30, "Game");
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)51);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(215, 120, 210, 30, "Latest Draw Number");
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)51);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
    } // Fl_Box* o
    { tatts_last_draw = new Fl_Output(215, 150, 210, 30);
    } // Fl_Output* tatts_last_draw
    { ozlotto_last_draw = new Fl_Output(215, 180, 210, 30);
    } // Fl_Output* ozlotto_last_draw
    { powerball_last_draw = new Fl_Output(215, 210, 210, 30);
    } // Fl_Output* powerball_last_draw
    { sfl_last_draw = new Fl_Output(215, 240, 210, 30);
    } // Fl_Output* sfl_last_draw
    { Fl_Box* o = new Fl_Box(425, 120, 210, 30, "Latest Draw Date");
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)51);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
    } // Fl_Box* o
    { ozlotto_last_date = new Fl_Output(425, 180, 210, 30);
    } // Fl_Output* ozlotto_last_date
    { powerball_last_date = new Fl_Output(425, 210, 210, 30);
    } // Fl_Output* powerball_last_date
    { sfl_last_date = new Fl_Output(425, 240, 210, 30);
    } // Fl_Output* sfl_last_date
    { tatts_last_date = new Fl_Output(425, 150, 210, 30);
    } // Fl_Output* tatts_last_date
    { Fl_Button* o = new Fl_Button(460, 25, 165, 25, "Download Results");
      o->callback((Fl_Callback*)cb_Download);
    } // Fl_Button* o
    main_window->end();
    main_window->resizable(main_window);
  } // Fl_Double_Window* main_window
  { update_window = new Fl_Double_Window(310, 235, "Update Results");
    update_window->user_data((void*)(this));
    { tatts_c = new Fl_Check_Button(25, 25, 165, 25, "Tattslotto");
      tatts_c->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* tatts_c
    { ozlotto_c = new Fl_Check_Button(25, 50, 165, 25, "Oz Lotto");
      ozlotto_c->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* ozlotto_c
    { powerball_c = new Fl_Check_Button(25, 75, 165, 25, "Powerball");
      powerball_c->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* powerball_c
    { sfl_c = new Fl_Check_Button(25, 100, 165, 25, "Set For Life");
      sfl_c->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* sfl_c
    { weekday_tatts_c = new Fl_Check_Button(25, 125, 250, 25, "Monday/Wednesday Tattslotto");
      weekday_tatts_c->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* weekday_tatts_c
    { Fl_Button* o = new Fl_Button(30, 190, 250, 30, "Update");
      o->callback((Fl_Callback*)update_results);
    } // Fl_Button* o
    { update_progress_bar = new Fl_Progress(0, 155, 310, 25);
      update_progress_bar->selection_color((Fl_Color)4);
    } // Fl_Progress* update_progress_bar
    update_window->end();
  } // Fl_Double_Window* update_window
  return update_window;
}

void DrawHistoryManagerGUI::update_results(Fl_Widget* w, void* userdata) {
  Fl_Widget *p = w->parent();
  while (p->parent()) p = p->parent();
  resultType ptr = *((resultType*)(&userdata));
  ((DrawHistoryManagerGUI*)p->user_data())->update_results_callback(w, ptr);
}
