// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "DrawHistoryManagerGUI.h"

void DrawHistoryManagerGUI::cb_Update_i(Fl_Button*, void*) {
  update_window->show();
}
void DrawHistoryManagerGUI::cb_Update(Fl_Button* o, void* v) {
  ((DrawHistoryManagerGUI*)(o->parent()->user_data()))->cb_Update_i(o,v);
}

void DrawHistoryManagerGUI::cb_View_i(Fl_Button*, void*) {
  init_result_view(R_TATTSLOTTO);
}
void DrawHistoryManagerGUI::cb_View(Fl_Button* o, void* v) {
  ((DrawHistoryManagerGUI*)(o->parent()->user_data()))->cb_View_i(o,v);
}

void DrawHistoryManagerGUI::cb_View1_i(Fl_Button*, void*) {
  init_result_view(R_POWERBALL);
}
void DrawHistoryManagerGUI::cb_View1(Fl_Button* o, void* v) {
  ((DrawHistoryManagerGUI*)(o->parent()->user_data()))->cb_View1_i(o,v);
}

void DrawHistoryManagerGUI::cb_View2_i(Fl_Button*, void*) {
  init_result_view(R_OZLOTTO);
}
void DrawHistoryManagerGUI::cb_View2(Fl_Button* o, void* v) {
  ((DrawHistoryManagerGUI*)(o->parent()->user_data()))->cb_View2_i(o,v);
}

void DrawHistoryManagerGUI::cb_View3_i(Fl_Button*, void*) {
  init_result_view(R_SET_FOR_LIFE);
}
void DrawHistoryManagerGUI::cb_View3(Fl_Button* o, void* v) {
  ((DrawHistoryManagerGUI*)(o->parent()->user_data()))->cb_View3_i(o,v);
}

void DrawHistoryManagerGUI::cb_View4_i(Fl_Button*, void*) {
  init_result_view(R_WEEKDAY_TATTSLOTTO);
}
void DrawHistoryManagerGUI::cb_View4(Fl_Button* o, void* v) {
  ((DrawHistoryManagerGUI*)(o->parent()->user_data()))->cb_View4_i(o,v);
}

Fl_Double_Window* DrawHistoryManagerGUI::make_window() {
  { main_window = new Fl_Double_Window(970, 810, "Results Manager");
    main_window->color((Fl_Color)12);
    main_window->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(0, 0, 970, 25, "Result Manager");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->selection_color(FL_FOREGROUND_COLOR);
      o->labelsize(18);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(625, 25, 75, 25, "Close");
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    { Fl_Box* o = new Fl_Box(205, 75, 135, 30, "Tattslotto");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(475, 75, 135, 30, "Oz Lotto");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(340, 75, 135, 30, "Powerball");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(610, 75, 135, 30, "Set For Life");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 75, 200, 30, "Game");
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)51);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 105, 200, 30, "Latest Draw Number");
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)51);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
    } // Fl_Box* o
    { tatts_last_draw = new Fl_Output(205, 105, 135, 30);
    } // Fl_Output* tatts_last_draw
    { ozlotto_last_draw = new Fl_Output(475, 105, 135, 30);
    } // Fl_Output* ozlotto_last_draw
    { powerball_last_draw = new Fl_Output(340, 105, 135, 30);
    } // Fl_Output* powerball_last_draw
    { sfl_last_draw = new Fl_Output(610, 105, 135, 30);
    } // Fl_Output* sfl_last_draw
    { Fl_Box* o = new Fl_Box(5, 135, 200, 30, "Latest Draw Date");
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)51);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
    } // Fl_Box* o
    { ozlotto_last_date = new Fl_Output(475, 135, 135, 30);
    } // Fl_Output* ozlotto_last_date
    { powerball_last_date = new Fl_Output(340, 135, 135, 30);
    } // Fl_Output* powerball_last_date
    { sfl_last_date = new Fl_Output(610, 135, 135, 30);
    } // Fl_Output* sfl_last_date
    { tatts_last_date = new Fl_Output(205, 135, 135, 30);
    } // Fl_Output* tatts_last_date
    { Fl_Button* o = new Fl_Button(415, 25, 210, 25, "Update/Download Results");
      o->callback((Fl_Callback*)cb_Update);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(205, 165, 135, 30, "View Results");
      o->callback((Fl_Callback*)cb_View);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(340, 165, 135, 30, "View Results");
      o->callback((Fl_Callback*)cb_View1);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(475, 165, 135, 30, "View Results");
      o->callback((Fl_Callback*)cb_View2);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(610, 165, 135, 30, "View Results");
      o->callback((Fl_Callback*)cb_View3);
    } // Fl_Button* o
    { resultViewTable = new ResultViewTable(15, 270, 955, 335);
      resultViewTable->box(FL_THIN_DOWN_FRAME);
      resultViewTable->color(FL_BACKGROUND_COLOR);
      resultViewTable->selection_color(FL_BACKGROUND_COLOR);
      resultViewTable->labeltype(FL_NORMAL_LABEL);
      resultViewTable->labelfont(0);
      resultViewTable->labelsize(28);
      resultViewTable->labelcolor(FL_FOREGROUND_COLOR);
      resultViewTable->align(Fl_Align(FL_ALIGN_TOP));
      resultViewTable->when(FL_WHEN_RELEASE);
      { new Fl_Output(40, 295, 25, 25);
      } // Fl_Output* o
      init_result_view(R_TATTSLOTTO);
      resultViewTable->end();
    } // ResultViewTable* resultViewTable
    { Fl_Box* o = new Fl_Box(745, 75, 135, 30, "Weekday Lotto");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { weekday_last_date = new Fl_Output(745, 135, 135, 30);
    } // Fl_Output* weekday_last_date
    { Fl_Button* o = new Fl_Button(745, 165, 135, 30, "View Results");
      o->callback((Fl_Callback*)cb_View4);
    } // Fl_Button* o
    { weekday_last_draw = new Fl_Output(745, 105, 135, 30);
    } // Fl_Output* weekday_last_draw
    main_window->end();
    main_window->resizable(main_window);
  } // Fl_Double_Window* main_window
  { update_window = new Fl_Double_Window(310, 235, "Update Results");
    update_window->user_data((void*)(this));
    { tatts_c = new Fl_Check_Button(25, 25, 165, 25, "Tattslotto");
      tatts_c->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* tatts_c
    { ozlotto_c = new Fl_Check_Button(25, 50, 165, 25, "Oz Lotto");
      ozlotto_c->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* ozlotto_c
    { powerball_c = new Fl_Check_Button(25, 75, 165, 25, "Powerball");
      powerball_c->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* powerball_c
    { sfl_c = new Fl_Check_Button(25, 100, 165, 25, "Set For Life");
      sfl_c->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* sfl_c
    { weekday_tatts_c = new Fl_Check_Button(25, 125, 250, 25, "Monday/Wednesday Tattslotto");
      weekday_tatts_c->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* weekday_tatts_c
    { Fl_Button* o = new Fl_Button(5, 190, 160, 30, "Update");
      o->callback((Fl_Callback*)update_results);
    } // Fl_Button* o
    { Fl_Progress* o = update_progress_bar = new Fl_Progress(0, 155, 310, 25);
      update_progress_bar->selection_color((Fl_Color)4);
      o->maximum(1);
      o->minimum(0);
      o->value(0);
    } // Fl_Progress* update_progress_bar
    { Fl_Button* o = new Fl_Button(175, 190, 130, 30, "Close");
      o->callback((Fl_Callback*)hide_parent);
    } // Fl_Button* o
    update_window->end();
  } // Fl_Double_Window* update_window
  return update_window;
}

void DrawHistoryManagerGUI::update_results(Fl_Widget* w, void* userdata) {
  Fl_Widget *p = w->parent();
  while (p->parent()) p = p->parent();
  
  ((DrawHistoryManagerGUI*)p->user_data())->update_results_callback(w, NULL);
}

void DrawHistoryManagerGUI::hide_parent(Fl_Widget *w, void* data) {
  (w->parent())->hide();
}
