// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "ResultManagerGUI.h"
#include <string>
#include "defs.h"
#include "types.h"
#include "ResultDownloader.h"
#include "HistoricResults.h"

Fl_Menu_Item ResultManagerGUI::menu_Update[] = {
 {"Tattslotto/GoldLotto/Lotto X", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Oz Lotto", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Powerball", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Set For Life", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Update All", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Double_Window* ResultManagerGUI::make_window() {
  { ResultManagerGUI = new Fl_Double_Window(700, 455, "Results Manager");
    ResultManagerGUI->color((Fl_Color)12);
    ResultManagerGUI->user_data((void*)(this));
    { Fl_Progress* o = new Fl_Progress(0, 430, 700, 25);
      o->selection_color((Fl_Color)4);
    } // Fl_Progress* o
    { Fl_Box* o = new Fl_Box(0, 0, 700, 25, "Result Manager");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)4);
      o->selection_color(FL_FOREGROUND_COLOR);
      o->labelsize(18);
      o->labelcolor((Fl_Color)3);
    } // Fl_Box* o
    { new Fl_Button(625, 25, 75, 25, "Close");
    } // Fl_Button* o
    { new Fl_Box(625, 50, 75, 25);
    } // Fl_Box* o
    { Fl_Menu_Button* o = new Fl_Menu_Button(480, 25, 145, 25, "Update");
      o->menu(menu_Update);
    } // Fl_Menu_Button* o
    { Fl_Box* o = new Fl_Box(5, 150, 210, 30, "Tattslotto");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 180, 210, 30, "Oz Lotto");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 210, 210, 30, "Powerball");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 240, 210, 30, "Set For Life");
      o->box(FL_BORDER_BOX);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 120, 210, 30, "Game");
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)51);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(215, 120, 210, 30, "Latest Draw Number");
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)51);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
    } // Fl_Box* o
    { new Fl_Output(215, 150, 210, 30);
    } // Fl_Output* o
    { new Fl_Output(215, 180, 210, 30);
    } // Fl_Output* o
    { new Fl_Output(215, 210, 210, 30);
    } // Fl_Output* o
    { new Fl_Output(215, 240, 210, 30);
    } // Fl_Output* o
    { Fl_Box* o = new Fl_Box(425, 120, 210, 30, "Latest Draw Date");
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)51);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
    } // Fl_Box* o
    { new Fl_Output(425, 180, 210, 30);
    } // Fl_Output* o
    { new Fl_Output(425, 210, 210, 30);
    } // Fl_Output* o
    { new Fl_Output(425, 240, 210, 30);
    } // Fl_Output* o
    { new Fl_Output(425, 150, 210, 30);
    } // Fl_Output* o
    ResultManagerGUI->end();
    ResultManagerGUI->resizable(ResultManagerGUI);
  } // Fl_Double_Window* ResultManagerGUI
  return ResultManagerGUI;
}
